export default {

  "id": "8a2a74685a89624f015a8cdff21402e2",
  "paperSystemQusetionType": [{
    "type": "6",
    "typeList": [{
      "id": "8a2a74685a89624f015a8ce045e502e9",
      "list": [{
        "studentGetScore": null,
        "surfaceScore": null,
        "id": "8a2a74685982d9020159977575ec5b20",
        "title": "GYW05540",
        "stem": "阅读下面的文字，完成后面的题目。\n　　艺术品的接受在过去并不被看作是重要的美学问题，20世纪解释学兴起，一个名为“接受美学”的美学分支应运而生，于是研究艺术品的接受成为艺术美学中的显学。\n　　过去，通常只是从艺术家的立场出发，将创作看作艺术家审美经验的结晶过程，作品完成就意味着创作完成。而从接受美学的角度来看，这一完成并不说明创作已经终结，它只说明创作的第一阶段告一段落，接下来是读者或现众、听众的再创作。由于未被阅读的作品的价值包括审美价值仅仅是一种可能的存在，只有通过阅读，它才转化为现实的存在，因此对作品的接受具有艺术本体的意义。也就是说，接受者也是艺术创作的主体之一。\n　　艺术文本即作品对于接受者来说具有什么意义呢？接受美学的创始人、德国的伊瑟尔说艺术文本是一个“召唤结构”，因为文本有“空白”“空缺” “否定”三个要素。所 谓“空白”是说它有一些东西没有表达出来，作者有意不写或不明写，要接受者用自己的生活经验与想象去补充；所谓“空缺”，是语言结构造成的各个图像间的空白，接受者在阅读文本时要把一个个句子表现的图像片断连接起来，整合成一个有机的图像系统；所谓“否定”指文本对接受者生活的现实具有否定的功能，它能引导接受者对现实进行反思和批判，由此可见，文本的召唤性需要接受者呼应和配合，完成艺术品的第二次创作，正如中国古典美学中的含蓄与简洁，其有限的文字常常引发出读者脑海中的丰富意象。\n　　接受者作为主体，他对文本的接受不是被动的，海德格尔提出“前理解”，即理解前的心理文化结构，这种结构影响着理解。理解不可能是文本意义的重现，而只能是文本与“前理解”的统一。这样，文本与接受就呈现出一种相互作用的关系：一方面文本在相当程度上规定了接受者理解的范围、方向，让理解朝它的本义靠拢；另一方面，文本不可能将接受者完全制约住、规范住，接受者必然会按照自己的方式去理解作品，于是不可避免地就会出现误读或创造。从某种意义上说，理解就是误读，创造也是误读，不要希望所有的接受者都持同样的理解，也不要希望所有的理解都与艺术家的本旨一致，那样并不意味着艺术作品的成功。\n　　文本一经产生就成为历史，它所表达的思想感情、所反映的生活，都只能是过去的， 而理解总是现在进行时。当我们接受历史上的艺术作品时，我们当然可以设身处地想象古人的生活，体验古人的思想感情，但我们毕竟是现代人，只能按照我们现在的心理文化结构去理解古人。当然，任何理解都只能是个体的理解，但个体毕竟是与群体相通的， 所以个体的理解中也有普遍性。理解作为现实的行为具有通向实践的品格，艺术品正是通过理解走向现实，并在生活中发挥作用的，不是别的，正是理解擦亮了艺术品的生命之光。\n　　（摘编自陈望衡《艺术是什么》）\n",
        "quesOption": "",
        "answer": "",
        "type": "6",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"1\"}]",
        "difficultStar": 3,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": null,
        "productions": "辨别筛选信息的方法",
        "productionCode": "0177001300080001",
        "score": 9.0,
        "enlargeId": "8a2a746858ce87510158e12b55cb592f",
        "knowledges": "辨别筛选信息",
        "costTime": null,
        "sort": 1,
        "questionNo": 1,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": null,
        "list": null,
        "knowledgeJson": null,
        "tree": [],
        "basetree": [],
        "componentQuestions": [{
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（1）下列关于原文内容的表述，正确的一项是（ &nbsp; ）",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"在接受美学诞生以前，人们只有一个认识：整个创作过程就是艺术家的审美经验不断结晶的过程，艺术品一旦形成，创作也就大功告成。\"},{\"optionKey\":\"B\",\"optionValue\":\"在过去，艺术品的接受并不属于美学的研究范围，而当接受美学诞生以后，关于艺术品的接受的研究就成为艺术美学中的一门显学。\"},{\"optionKey\":\"C\",\"optionValue\":\"接受美学认为，艺术品在艺术家手中产生出来，这只是艺术创作的第一阶段，读者、观众、听众对艺术品的接受是艺术创作的完成。\"},{\"optionKey\":\"D\",\"optionValue\":\"通过读者、观众和听众的接受，艺术作品的价值才从一种可能的存在转化为现实的存在，从这个意义上说，接受也属于艺术创作的一部分。\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"A.在接受美学诞生以前，人们<span style=\\\"text-decoration: underline;\\\">只有一个</span>认识：整个创作过程就是艺术家的审美经验不断<span style=\\\"text-decoration: underline;\\\">结晶的过程</span>，艺术品一旦形成，创作也就大功告成。检索选项对应的文句：过去，<span style=\\\"text-decoration: underline;\\\">通常只是</span>从艺术家的立场出发，将创作看作艺术家审美经验的<span style=\\\"text-decoration: underline;\\\">结晶过程</span>，作品完成就意味着创作完成。\\n聚焦选项考查的实质：“通常只是”表明“只有一个”，此项错误。B.在过去，<span style=\\\"text-decoration: underline;\\\">艺术品的接受</span>并不属于美学的研究范围，而当接受美学诞生以后，关于艺术品的接受的研究就成为艺术美学中的一门显学。检索选项对应文句：艺术品的接受在过去并<span style=\\\"text-decoration: underline;\\\">不被看作是重要的</span>美学问题，20世纪解释学兴起，一个名为“接受美学”的美学分支应运而生，于是研究艺术品的接受成为艺术美学中的显学。\\n聚焦选项考查的实质：“不被看作是重要的”是“不属于”，此项错误。\\nC.接受美学认为，艺术品在艺术家手中产生出来，这只是艺术创作的第一阶段，读者、观众、听众对艺术品的接受是艺术<span style=\\\"text-decoration: underline;\\\">创作的完成。</span>检索选项对应的文句：而从接受美学的角度来看，这一完成并不说明创作已经终结，它只说明创作的第一阶段告一段落，接下来是读者或现众、听众的<span style=\\\"text-decoration: underline;\\\">再创作</span>。\\n聚焦选项考查的实质：“再创作”是“创作的完成”，此项错误。\\nD.通过读者、观众和听众的接受，艺术作品的价值才从一种可能的存在转化为现实的存在，从这个意义上说，接受也属于艺术创作的一部分。检索选项对应的文句：由于未被阅读的作品的价值包括审美价值仅仅是一种可能的存在，只有通过阅读，它才<span style=\\\"text-decoration: underline;\\\">转化为现实的存在</span>，因此对作品的接受具有艺术本体的意义，也就是说，接受者也是<span style=\\\"text-decoration: underline;\\\">艺术创作的主体之一</span>。\\n聚焦选项考查的实质：“艺术创作的主体之一”意味着“属于艺术创作的一部分”，正确。\\n\"}]",
          "questionNo": 1,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550008",
            "name": "辨别筛选信息",
            "isRight": 0,
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": "0177001300080001",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "辨别筛选信息的方法",
            "basecodeVo": "0177001300080001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 0
          }],
          "id": "8a2a74685a89624f015a8ce15fb102f7",
          "answer": "D",
          "type": "1",
          "score": 3.0,
          "sort": 1,
          "quesId": "8a2a74685a89624f015a8ce15f9f02f6",
          "product": "辨别筛选信息的方法",
          "productCode": "0177001300080001",
          "knowledge": "辨别筛选信息",
          "knowledgeCode": "017700130008",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（2）下列理解和分析，不符合原文意思的一项是（ &nbsp; ）",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"文本之所以是一个“召唤结构”，一个原因就是它有一些内容有意不写或不明写， 需要接受者用自己的生活经验与想象去补充。\"},{\"optionKey\":\"B\",\"optionValue\":\"作品被艺术家创作出来以后就成为历史，作品是通过接受者的理解而存活于现实，并发挥作用的。从这个意义上说，作品的生命力存在于理解之中。\"},{\"optionKey\":\"C\",\"optionValue\":\"“前理解”是接受者在理解文本以前的心理文化结构，由于接受者对文本的接受不是被动的，所以这种结构会影响接受者对文本的理解。\"},{\"optionKey\":\"D\",\"optionValue\":\"文本的“否定”要素具有对接受者所生活的现实加以否定的功能，这种功能是通过接受者接受文本并对现实进行反思和批判而实现的。\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"A.文本之所以是一个“<span style=\\\"text-decoration: underline;\\\">召唤结构</span>”，<span style=\\\"text-decoration: underline;\\\">一个原因</span>就是它有一些内容有意不写或不明写， 需要接受者用自己的生活经验与想象去补充。检索选项对应文句：德国的伊瑟尔说艺术文本是一个“<span style=\\\"text-decoration: underline;\\\">召唤结构</span>”，因为文本有“空白”“空缺” “否定”<span style=\\\"text-decoration: underline;\\\">三个要素</span>。所谓“空白”是说它有一些东西没有表达出来，作者有意不写或不明写，要接受者用自己的生活经验与想象去补充。\\n聚焦选项考查的实质：“三个要素之一”是“一个原因”，正确。B.作品被艺术家创作出来以后就成为历史，作品是通过接受者的理解而存活于现实，<span style=\\\"text-decoration: underline;\\\">并发挥作用</span>的。从这个意义上说，<span style=\\\"text-decoration: underline;\\\">作品的生命力存在于理解之中。</span>检索选项对应的文句：文本一经产生就成为历史……理解作为现实的行为具有通向实践的品格，艺术品正是通过理解走向现实，并在生活中<span style=\\\"text-decoration: underline;\\\">发挥作用</span>的，不是别的，正是<span style=\\\"text-decoration: underline;\\\">理解擦亮了艺术品的生命之光。</span>\\n聚焦选项考查的实质：“理解擦亮了艺术品的生命之光”表明“作品的生命力存在于理解之中”，正确。\\nC.“前理解”是接受者在理解文本以前的<span style=\\\"text-decoration: underline;\\\">心理文化结构</span>，由于接受者对文本的接受不是被动的，<span style=\\\"text-decoration: underline;\\\">所以这种结构会影响</span>接受者对文本的理解。检索选项对应的文句：接受者作为主体，他对文本的接受不是被动的，海德格尔提出“前理解”，即理解前的<span style=\\\"text-decoration: underline;\\\">心理文化结构</span>，<span style=\\\"text-decoration: underline;\\\">这种结构影响</span>着理解。\\n聚焦选项考查的实质：“这种结构影响”是“所以这种结构会影响”，此项错误。\\nD.文本的“<span style=\\\"text-decoration: underline;\\\">否定</span>”要素具有对接受者所生活的现实加以否定的功能，这种功能是<span style=\\\"text-decoration: underline;\\\">通过接受者接受文本</span>并对现实进行反思和批判而实现的。检索选项对应的文句：所谓“<span style=\\\"text-decoration: underline;\\\">否定</span>”指文本对接受者生活的现实具有否定的功能，它能<span style=\\\"text-decoration: underline;\\\">引导接受者</span>对现实进行反思和批判。\\n聚焦选项考查的实质：“引导接受者”意味着“通过接受者接受文本”，正确。\\n\\n\"}]",
          "questionNo": 2,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550008",
            "name": "辨别筛选信息",
            "isRight": 0,
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": "0177001300080001",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "辨别筛选信息的方法",
            "basecodeVo": "0177001300080001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 0
          }],
          "id": "8a2a74685a89624f015a8ce15fb602f8",
          "answer": "C",
          "type": "1",
          "score": 3.0,
          "sort": 2,
          "quesId": "8a2a74685a89624f015a8ce15f9f02f6",
          "product": "辨别筛选信息的方法",
          "productCode": "0177001300080001",
          "knowledge": "辨别筛选信息",
          "knowledgeCode": "017700130008",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（3）根据原文内容，下列理解和分析不正确的一项是（ ）&nbsp;\n",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"理解就是误读，创造也是误读，理解距离艺术作品的本义越远，就越是具有创造性，正如《西厢记》之于《莺莺传》、《金瓶梅》之于《水浒传》。\"},{\"optionKey\":\"B\",\"optionValue\":\"文本在一定程度上规定了接受者理解的范围和方向，所以即使我们今天阅读历史上的艺术作品，也可以在相当程度上了解古人的生活，体验古人的思想感情。\"},{\"optionKey\":\"C\",\"optionValue\":\"作为接受者的个体毕竟生活在群体之中，其思维和观念与群体是相通的，因此接受者们对于同一文本的理解即使千姿百态，也不可能完全没有同—性。\"},{\"optionKey\":\"D\",\"optionValue\":\"中国古典美学中强调的含蓄和简洁可以说是艺术作品召唤性的体现，含蓄的美在于从有限中表现无限，简洁的美在于以少胜多，以简驭繁。\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"A.<span style=\\\"text-decoration: underline;\\\">理解就是误读</span>，创造也是误读，<span style=\\\"text-decoration: underline;\\\">理解距离艺术作品的本义越远，就越是具有创造性</span>，正如《西厢记》之于《莺莺传》、《金瓶梅》之于《水浒传》。检索选项对应文句：<span style=\\\"text-decoration: underline;\\\">从某种意义上说，理解就是误读</span>，创造也是误读，不要希望所有的接受者都持同样的理解，也不要希望所有的理解都与艺术家的本旨一致，那样并不意味着艺术作品的成功。\\n聚焦选项考查的实质：可去掉“从某种意义上说”；可添加“理解距离艺术作品的本义越远，就越是具有创造性”，此项错误。\\nB.文本在一定程度上规定了接受者理解的范围和方向，<span style=\\\"text-decoration: underline;\\\">所以即使我们今天阅读历史上的艺术作品，也可以在相当程度上了解古人的生活，体验古人的思想感情。</span>检索选项对应文句：一方面文本在相当程度上规定了接受者理解的范围、方向，<span style=\\\"text-decoration: underline;\\\">让理解朝它的本义靠拢</span>。\\n聚焦选项考查的实质：“让理解朝它的本义靠拢”“所以即使我们今天阅读历史上的艺术作品，也可以在相当程度上了解古人的生活，体验古人的思想感情”，正确。\\nC.作为接受者的<span style=\\\"text-decoration: underline;\\\">个体毕竟生活在群体之中</span>，其思维和观念与群体是相通的，因此接受者们对于同一文本的<span style=\\\"text-decoration: underline;\\\">理解即使千姿百态，也不可能完全没有同—性。</span>检索选项对应文句：当然，任何理解都只能是个体的理解，但<span style=\\\"text-decoration: underline;\\\">个体毕竟是与群体相通的</span>， 所以<span style=\\\"text-decoration: underline;\\\">个体的理解中也有普遍性</span>。\\n聚焦选项考查的实质：“个体的理解中也有普遍性”意味着“理解不可能完全没有同—性”，正确。D.<span style=\\\"text-decoration: underline;\\\">中国古典美学</span>中强调的含蓄和简洁可以说是艺术作品召唤性的体现，含蓄的美在于从有限中表现无限，简洁的美在于<span style=\\\"text-decoration: underline;\\\">以少胜多，以简驭繁。</span>检索选项对应文句：由此可见，文本的召唤性需要接受者呼应和配合，完成艺术品的第二次创作，正如<span style=\\\"text-decoration: underline;\\\">中国古典美学</span>中的含蓄与简洁，其<span style=\\\"text-decoration: underline;\\\">有限的文字常常引发出读者脑海中的丰富意象。</span>\\n聚焦选项考查的实质：“有限的文字常常引发出读者脑海中的丰富意象”是“从有限中表现无限”“以少胜多，以简驭繁”，正确。\\n\\n\"}]",
          "questionNo": 3,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550008",
            "name": "辨别筛选信息",
            "isRight": 0,
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": "0177001300080001",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "辨别筛选信息的方法",
            "basecodeVo": "0177001300080001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 0
          }],
          "id": "8a2a74685a89624f015a8ce15fbb02f9",
          "answer": "A",
          "type": "1",
          "score": 3.0,
          "sort": 3,
          "quesId": "8a2a74685a89624f015a8ce15f9f02f6",
          "product": "辨别筛选信息的方法",
          "productCode": "0177001300080001",
          "knowledge": "辨别筛选信息",
          "knowledgeCode": "017700130008",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }],
      "itemContent": "选择题阅读",
      "itemType": "6",
      "enlargeType": null,
      "itemScore": 9.0,
      "sort": 1,
      "logicType": "q_610"
    }, {
      "id": "8a2a74685a89624f015a8ce07d5d02eb",
      "list": [{
        "studentGetScore": null,
        "surfaceScore": null,
        "id": "8a2a74685982d902015997a0149f5b39",
        "title": "GYW05541",
        "stem": "阅读文本，回答后面问题。\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;朱东润自传\n&nbsp; &nbsp; &nbsp; 1896年我出生在江苏泰兴一个失业店员的家庭，早年生活艰苦，所受的教育也存在着一定的波折。21岁我到梧州担任广西第二中学的外语教师，23岁调任南通师范学校教师。\n&nbsp; &nbsp; &nbsp; 1929年4月间，我到武汉大学担任外语讲师，从此我就成为大学教师。那时武汉大学的文学院长是闻一多教授，他看到中文系的教师实在太复杂，总想来一些变动。用近年的说法，这叫做掺沙子。我的命运是作为沙子而到中文系开课的。\n&nbsp; &nbsp; &nbsp; 大约是1939年吧，一所内迁的大学的中文系在学年开始，出现了传记研究这一个课，其下注明本年开韩柳文。传记文学也好，韩柳文学也不妨，但是怎么会在传记研究这个总题下面开韩柳文呢？在当时的大学里，出现的怪事不少，可是这一项多少和我的兴趣有关，这就决定了我对于传记文学献身的意图。\n&nbsp; &nbsp; &nbsp; 《四库全书总目》有传记类，指出《晏子春秋》为传之祖，《孔子三朝记》为记之祖，这是三百年前的看法，现在用不上了。有人说《史记》《汉书》为传记之祖，这个也用不上。《史》《汉》有互见法，对于一个人的评价，常常需要通读全书多卷，才能得其大略。可是在传记文学里，一个传主只有一本书，必须在这本书里把对他的评价全部交代。\n&nbsp; &nbsp; &nbsp; 是不是古人所作的传、行状、神道碑这一类的作品对于近代传记文学的写作有什么帮助呢？也不尽然。古代文人的这类作品，主要是对于死者的歌颂，对于近代传记文学是没有什么用处的。这些作品，毕竟不是传记文学。\n除了史家和文人的作品以外，是不是还有值得提出的呢？有的，这便是所谓别传。别传的名称，可能不是作者的自称而是后人认为有别于正史，因此称为“别传”。有些简单一些，也可称为传叙。这类作品写得都很生动，没有那些阿谀奉承之辞，而且是信笔直书，对于传主的错误和缺陷，都是全部奉陈。\n&nbsp; &nbsp; &nbsp; 是不是可以从国外吸收传记文学的写作方法呢？当然可以，而且有此必要。但是不能没有一个抉择。罗马时代的勃路塔克是最好的了，但是他的时代和我们相去太远，而且他的那部大作，所着重的是相互比较而很少对于传主的刻画，因此我们只能看到一个大略而看不到入情入理的细致的分析。\n&nbsp; &nbsp; &nbsp; 英国的《约翰逊博士传》是传记文学中的不朽名作，英国人把它推重到极高的地位。这部书的细致是到了一个登峰造极的地位，但是的确也难免有些琐碎。而且由于约翰逊并不处于当时的政治中心，其人也并不能代表英国的一般人物，所以这部作品不是我们必须模仿的范本。\n&nbsp; &nbsp; &nbsp; 是不是我国已经翻译过来的《维多利亚女王传》可以作为范本呢？应当说是可以，由于作者着墨无多，处处显得“颊上三毫”的风神。可是中国文人相传的做法，正是走的一样的道路，所以无论近代人怎么推崇这部作品，总还不免令人有“穿新鞋走老路”的戒心。\n&nbsp; &nbsp; &nbsp; 国内外的作品读过一些，也读过法国评论家莫洛亚的传记文学理论，是不是对于传记文学就算有些认识呢？不算，在自己没有动手创作之前，就不能算是认识。\n&nbsp; &nbsp; &nbsp; 这时是1940年左右，中国正在艰苦抗战，我只身独处，住在四川乐山的郊区，每周得进城到学校上课，生活也很艰苦。家乡已经陷落了，妻室儿女，一家八口，正在死亡线上挣扎。我决心把研读的各种传记作为范本，自己也写出一本来。我写谁呢？我考虑了好久，最后决定写明代的张居正。第一，因为他能把一个充满内忧外患的国家拯救出来，为垂亡的明王朝延长了七十年的寿命。第二，因为他不顾个人的安危和世人的唾骂，终于完成历史赋予他的使命。他不是没有缺点的，但是无论他有多大的缺点，他是唯一能够拯救那个时代的人物。&nbsp;\n（有删改）\n相关链接\n①自传和传人，本是性质类似的著述，除了因为作者立场的不同，因而有必要的区别以外，原来没有很大的差异。但是在西洋文学里，常会发生分类的麻烦。我们则传叙二字连用指明同类的文学。同时因为古代的用法，传人曰传，自叙曰叙，这种分别的观念，是一种原有的观念，所以传叙文学，包括叙、传在内，丝毫不感觉牵强。(朱东润《关于传叙文学的几个名词》）\n②朱先生确是有儒家风度的学者，一身正气，因此他所选择的传主对象，差不多都是关心国计民生的有为之士。他强调关切现实，拯救危亡，尊崇气节与品格。这都是可以理解的。（傅璇琮《理性的思索和情感的倾注——读朱东润先生史传文学随想》）\n",
        "quesOption": "",
        "answer": "",
        "type": "6",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"1\"}]",
        "difficultStar": 2,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": null,
        "productions": "分析情节及结构安排的方法@概括内容要点的方法@赏析文章表达技巧的方法@辨别筛选信息的方法",
        "productionCode": "0177001300030001@0177001300040003@0177001300070003@0177001300080001",
        "score": 12.0,
        "enlargeId": "8a2a7468559088eb015594f5b62800f3",
        "knowledges": "概括文章主题及要点@品味语言表达艺术@辨别筛选信息@理清文章结构及情节",
        "costTime": null,
        "sort": 1,
        "questionNo": 2,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": null,
        "list": null,
        "knowledgeJson": null,
        "tree": [],
        "basetree": [],
        "componentQuestions": [{
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（1）下列对材料有关内容的分析和概括，最恰当的一项是（ ）\n",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"朱东润虽然认可国外的传记文学，但却担心“穿新鞋走老路”，因此拒绝把近代人推崇的《维多利亚女王传》作为写作范本。\"},{\"optionKey\":\"B\",\"optionValue\":\"朱东润虽然认为“传叙文学”的说法更加科学，但为了避免常会发生的分类麻烦，还是在自传中采用了“传记文学”的说法。\"},{\"optionKey\":\"C\",\"optionValue\":\"当年有所大学的中文系开传记研究课，课程内容却是韩愈、柳宗元的古文，朱东润就是因为这件事决心献身传记文学的研究。\"},{\"optionKey\":\"D\",\"optionValue\":\"“我的命运是作为沙子而到中文系开课的”，这样的表述与其说写出了自己过去的经历，不如说反映了朱东润写自传时的心态。\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"A.朱东润虽然认可国外的传记文学，但却担心“穿新鞋走老路”，因此拒绝把近代人推崇的《维多利亚女王传》作为写作范本。检索原文对应文句：<span style=\\\"text-decoration: underline;\\\">是不是我国已经翻译过来的《维多利亚女王传》可以作为范本呢？</span>应当说是<span style=\\\"text-decoration: underline;\\\">可以</span>，由于作者着墨无多，处处显得“颊上三毫”的风神。可是中国文人相传的做法，正是走的一样的道路，所以无论近代人怎么推崇这部作品，<span style=\\\"text-decoration: underline;\\\">总还不免令人有“穿新鞋走老路”的戒心。</span>\\n聚焦选项考查实质：我们从逻辑上无法推导出“拒绝把近代人推崇的《维多利亚女王传》作为写作范本”的结论，“因此拒绝”分析不正确，此项错误。\\nB.朱东润虽然认为“传叙文学”的说法更加科学，但为了避免常会发生的分类麻烦，<span style=\\\"text-decoration: underline;\\\">还是在自传中采用了“传记文学”的说法。</span>检索原文对应文句：但是在西洋文学里，常会<span style=\\\"text-decoration: underline;\\\">发生分类的麻烦</span>。我们则<span style=\\\"text-decoration: underline;\\\">传叙二字连用指明同类的文学。</span>聚焦选项考查实质：相关链接①说的是“传叙文学”概念的使用可以避免西洋文学里常会发生的分类的麻烦，“还是在自传中采用了‘传记文学’的说法”，分析不正确，此项错误。\\nC.当年有所大学的中文系开传记研究课，课程内容却是韩愈、柳宗元的古文，朱东润<span style=\\\"text-decoration: underline;\\\">就是因为这件事</span>决心献身传记文学的研究。检索原文对应文句：在当时的大学里，出现的怪事不少，可是<span style=\\\"text-decoration: underline;\\\">这一项多少和我的兴趣有关</span>，这就决定了我对于传记文学献身的意图。聚焦选项考查实质：忽视了细节“这一项多少和我的兴趣有关”，“朱东润就是因为这件事”分析错误。\\nD.“我的命运是作为沙子而到中文系开课的”这样的表述与其说写出了自己过去的经历，不如说反映了朱东润写自传时的心态。检索原文对应文句：那时武汉大学的文学院长是闻一多教授，他看到中文系的教师实在太复杂，总想来一些变动。<span style=\\\"text-decoration: underline;\\\">用近年的说法，这叫做掺沙子</span>。我的命运是作为沙子而到中文系开课的。\\n聚焦选项考查实质：“掺沙子”这样一个“近年的说法”的采用直接表明，本文的写作不可能与具体的历史语境和写作者的心态无关。此项正确。\\n\"}]",
          "questionNo": 1,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550003",
            "name": "理清文章结构及情节",
            "isRight": 0,
            "sons": [{
              "idVo": "785500030008",
              "nameVo": "分析小说情节的方法",
              "basecode": "0177001300030001",
              "isRight": 0,
              "typecode": null
            }]
          }, {
            "id": "78550008",
            "name": "辨别筛选信息",
            "isRight": 0,
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": "0177001300080001",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "分析小说情节的方法",
            "basecodeVo": "0177001300030001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500030008",
              "nameVo": "分析小说情节的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 0
          }, {
            "basenameVo": "辨别筛选信息的方法",
            "basecodeVo": "0177001300080001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 0
          }],
          "id": "8a2a74685a89624f015a8ce20fe402fe",
          "answer": "D",
          "type": "1",
          "score": 3.0,
          "sort": 1,
          "quesId": "8a2a74685a89624f015a8ce20fcf02fd",
          "product": "分析情节及结构安排的方法@辨别筛选信息的方法",
          "productCode": "0177001300030001@0177001300080001",
          "knowledge": "理清文章结构及情节@辨别筛选信息",
          "knowledgeCode": "017700130003@017700130008",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 4.0,
          "surfaceScore": null,
          "stem": "（2）简述朱东润的传记文学观的形成过程。\n",
          "quesOption": "{\"optionKey\":\"null\",\"optionValue\":\"null\"}",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"检索、加工重要信息：\\n\\n第三段——出于大学授课需要和自己的兴趣，决定献身传记文学。\\n第四段——中国古代的《晏子春秋》《孔子三朝记》《史记》《汉书》等史家作品不是可以遵循的传记文学。\\n第五段——“传、行状、神道碑”一类古人文人作品也不是传记文学。\\n第六段——中国古代的“别传”有一定价值。\\n第七段——从国外吸收传记文学的写作方法，首先做好抉择。\\n第八段——鉴别国外传记文学，即使如《约翰逊博士传》这种不朽名作，也实事求是地认识。\\n第九段——又如《维多利亚女王传》，可以作为范本，也不能妨碍独创，要有戒心，\\n第十段——广泛阅读国内外传记作品，还读过莫洛亚的传记文学理论，尤其要自己动手创作。\\n第十一段——以研读的各种传记作为范本，选择关心国计民生的有为之士张居正做传主，开始自己的传记文学创作。朱东润传记文学观的形成过程，结合材料简析如下：①出于大学授课需要和自己的兴趣，决定献身传记文学；②广泛阅读国内传记作品，做出鉴别，《晏子春秋》《孔子三朝记》《史记》《汉书》等史家作品不是可以遵循的传记文学，“传、行状、神道碑”一类的古代文人作品也不是传记文学，“别传”有一定价值；③吸收国外传记文学的写作方法，首先做好抉择和鉴别，实事求是的认识《约翰逊博士传》这种不朽名作，以《维多利亚女王传》作为范本，但存有戒心，不能妨碍独创\\n\"}]",
          "questionNo": 2,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 1,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550004",
            "name": "概括文章主题及要点",
            "isRight": 1,
            "sons": [{
              "idVo": "785500040009",
              "nameVo": "概括内容要点的方法",
              "basecode": "0177001300040003",
              "isRight": 1,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "概括内容要点的方法",
            "basecodeVo": "0177001300040003",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500040009",
              "nameVo": "概括内容要点的方法",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce20fe902ff",
          "answer": "①广泛阅读古今中外的传记作品，如《史记》《汉书》《约翰逊博士传》《维多利亚女王传》等，并比较它们的异同；②深入研究传记文学理论，辨析不同概念，如阅读莫洛亚的传记文学理论，分辨史传、别传、自传、传叙文学等；③进行传记文学写作实践，如给张居正写传。\n",
          "type": "5",
          "score": 4.0,
          "sort": 2,
          "quesId": "8a2a74685a89624f015a8ce20fcf02fd",
          "product": "概括内容要点的方法",
          "productCode": "0177001300040003",
          "knowledge": "概括文章主题及要点",
          "knowledgeCode": "017700130004",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 5.0,
          "surfaceScore": null,
          "stem": "（3）本文有什么特点？简要分析。\n",
          "quesOption": "{\"optionKey\":\"null\",\"optionValue\":\"null\"}",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"《朱东润自传》的主要内容是关于传记文学的，本文内容“偏重学术经历，主要写自己的传记文学观及其形成过程”，朱东润又将自己的学术经历和生平融合在一起叙述，不仅加强了关于传记文学的讨论与自传的有机关系，而且将自己对于学术研究的态度渗透到字里行间，很好地呈现了他自己的学术背后的家国情怀。也就是说，学术对于朱东润来说，是他的生平不可分割的部分，是他关切现实的一种方式。这进一步说明，学者的自传是特殊的，往往也就是一种学术自传。\\n或许是深知学者自传的特殊性，也深知学术话题的读者有限，朱东润有意采用了一种平易近人的叙述风格。从本文来看，可以发现作者用语平易，穿插使用口语，有问有答，如“是不是对于传记文学就算有些认识呢”“我写谁呢”等，就像和老朋友闲谈一样。\\n\"}]",
          "questionNo": 3,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 1,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550007",
            "name": "品位语言表达艺术",
            "isRight": 1,
            "sons": [{
              "idVo": "785500070009",
              "nameVo": "赏析文章表达技巧的方法",
              "basecode": "0177001300070003",
              "isRight": 1,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "赏析文章表达技巧的方法",
            "basecodeVo": "0177001300070003",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500070009",
              "nameVo": "赏析文章表达技巧的方法",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce2100c0300",
          "answer": "①偏重学术经历，主要写自己的传记文学观及其形成过程；②写生平与写学术二者交融，呈现学术背后的家国情怀；③行文平易自然，穿插使用口语，就像和老朋友闲谈一样。\n",
          "type": "5",
          "score": 5.0,
          "sort": 3,
          "quesId": "8a2a74685a89624f015a8ce20fcf02fd",
          "product": "赏析文章表达技巧的方法",
          "productCode": "0177001300070003",
          "knowledge": "品味语言表达艺术",
          "knowledgeCode": "017700130007",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }, {
        "studentGetScore": null,
        "surfaceScore": null,
        "id": "8a2a74685982d902015997ae02455b41",
        "title": "GYW05542",
        "stem": "阅读下面的文字，完成文后题目。\n走正门\n王春迪\n老街有句俗语：夏府的地，货府的房，海府的银子用斗量。贺家发迹早，起初，海爷还是个小油贩子时，贺家就已经钟鸣鼎食，门阔院深,人称“贺丰街”了。\n然而，家有数座金山，不敌一个败子。后来，贺府家道中落，只能靠典当度日。一日，海爷路过贺府门前，看到有个不肖子孙正在卖一只枯瘦的看门狗，海爷不禁喟叹，花无百日红，人无千日好。昔日金玉满堂的贺府，如今只剩下一个金砖碧瓦做的空壳了。\n贺府后来卖给了海爷。因为地势高，地段好，海爷用它做起了油行的门面。贺府后院有个百步宽的天井，青砖铺就，四周景色幽静。还有几棵松柏，枝繁叶茂，傲然挺拔。如此花园，中间竟然立着贺家的祠堂，迁也迁不走，拆又不能拆，看着让人堵得慌。\n起初，每逢清明，贺家的子孙还三三两两地来祭祖。后来便不再有人来了。常有人跟海爷建议，这帮不肖子孙把老祖宗的家底都给败光了，也没脸来了，干脆把那个祠堂拆了吧。\n海爷却说，不可。\n后院鸽子多，鸽子屎常落得到处都是，海爷吩咐下人，隔些日子把贺家的祠堂打扫干净。到了清明，贺家没人来，海爷还让人烧香点烛，更新一些被老鼠啃坏的牌位。\n转眼几十个春秋，海爷已白发苍苍。一日，日过三竿，一阵锣鼓开道，老街的百姓跟水一样涌过去，随即，又像拍在岩石上一样分在两边。海爷隐约看到，一个八人抬的轿子在人群中似水浪般起伏。鸣锣十一响！这排场，唯京官才有！海爷微微闭着眼，低着头，垂着手，腰杆子挺直地跪在地上。身后的家人，有的窃窃私语，有的自言自语，求佛保佑，有的甚至浑身发抖，跪在地上半边身子都斜了。\n不一会儿，轿子停在了海爷府前，下来一个官人，下了轿，经过海爷时，像经过一个脚底下的石子儿，啥也没说，径直走进海爷的油行。身后，知府、知县以及各级官员都低着头，鱼贯而入。街坊们瞧这架势，心想，生意人恩怨多，海爷得罪人了。\n海爷的几个儿子，嘴止不住地叨叨着怎么办，怎么办呀。海爷静静地回过头，眼神一扫，大伙不敢言语了，同时腰杆子也挺了起来。\n一阵嘈杂的脚步声传来，官人从油行里走了出来，到海爷跟前将海爷扶了起来。海爷觉得此人两手温软有力，微微抬头，见他天庭饱满，地阁方圆，髯须飘逸，两肩圆厚，一副贵人之相。再看那官服，绣的是孔雀，顶戴蓝宝石花翎。未等海爷说话，官人便说，本官乃贺家后人，一别数十年，如今故地重游，旧迹难辨，唯有当年祠堂，托您照料，仿如昨日。本官不胜感激，刚才失礼，颇有得罪。说着，官人要弯腰拜谢，被海爷一把托住。海爷气定神闲地微微一笑，道，举手之劳，荣幸之至。随后，两人有说有笑，一同走进了昔日的贺府。\n当日，老街的每一个角落都在谈论着这件事，大伙都觉得，多亏海爷当初的仁义。倘若当初海爷一冲动把祠堂给拆了，保不准今儿个会出什么事情。\n一日，外面下着大雨，海爷闲来无事，把几个儿子儿媳妇叫到跟前喝茶，海爷若无其事地问他们，知道当初为啥我没拆贺家的祠堂吗？\n小儿媳鬼精，抢嘴说，是老爷您仁义。\n海爷笑笑，抿了一口茶，起身，眼睛望着窗外,好似看到了几十年前的情景。海爷说，贺家人搬走后的头几年，贺家还有不少后人来祭祖，其他人来的时候，都跟老鼠似的钻进钻出，拜祭时，有的说说笑笑，有的哭得撕心裂肺，进进出出，都走侧门，怕遇到熟人。\n唯有一个年轻女人，一手拎着篮子，一手领着一个孩子，清早最先来。娘儿俩大大方方地从正门进来，进来后，先将祠堂里里外外擦洗一遍，然后从篮子里拿出一个干净的蒲团，让孩子端端正正地跪拜。拜祭完，整理好衣裳，再昂首阔步地走出去。娘儿俩穿的都是粗布衣服，有的地方还带着点补丁，却十分干净。这样的穿着，从富丽堂皇的大门进出，难免会被众人指点议论，但那娘儿俩，始终抬头挺胸，遇到认识的街坊，还让孩子有礼有节地问好。\n海爷说，贺家有这样的娘儿俩，谁还敢拆他家的祠堂？这么些年了，也不知道那天那个官人，是不是当年那个孩子？\n小儿媳没弄懂，嘀咕道，不就是没走侧门走正门吗？这有啥啊？海爷听罢，长叹一声，背着手，回屋去了。 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;(原文有删改）\n",
        "quesOption": "",
        "answer": "",
        "type": "6",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"1\"}]",
        "difficultStar": 2,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": null,
        "productions": "分析情节及结构安排的方法@分析文章标题作用的方法@概括人物性格特点的方法@辨别筛选信息的方法",
        "productionCode": "0177001300030001@0177001300040001@0177001300060002@0177001300080001",
        "score": 14.0,
        "enlargeId": "8a2a7468559088eb015594f5b62800f3",
        "knowledges": "概括文章主题及要点@分析作品形象，把握人物性格@辨别筛选信息@理清文章结构及情节",
        "costTime": null,
        "sort": 2,
        "questionNo": 3,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": null,
        "list": null,
        "knowledgeJson": null,
        "tree": [],
        "basetree": [],
        "componentQuestions": [{
          "userAnswerResul": "A",
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（1）下列对小说思想内容和艺术特色的分析和鉴赏，不恰当的两项是（ ）\n",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"小说开头以老街上的“夏府的地，贺府的房，海府的银子用斗量”这一俗语开篇，主要是为了引出下文对贺家的情况的介绍，并为贺家、海家两家的遭遇埋下伏笔。\"},{\"optionKey\":\"B\",\"optionValue\":\"起初，每至清明，贺家的子孙三三两两前来祭祖,后来便不再有人来了，这说明贺家人的祭祖观念随着家境的变化而变淡。\"},{\"optionKey\":\"C\",\"optionValue\":\"做了京官的贺家后人返乡时，海爷的家人“有的甚至浑身发抖，跪在地上半边身子都斜了”，说明海爷的家人因得罪了贺家而害怕。\"},{\"optionKey\":\"D\",\"optionValue\":\"海爷的小儿媳是个鬼精且有城府的人，她先是抢先回答海爷的话，称赞海爷，后来又嘀咕，都是为了讨好海爷。\"},{\"optionKey\":\"E\",\"optionValue\":\"小说善于通过细节刻画海爷，迎接京官时的“闭眼”“低头”“垂手”“腰杆子挺直”及下文的“微微一笑”都将人物刻画得栩栩如生。\\n\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"C项 回到文段中进行检索:“鸣锣<span style=\\\"text-decoration: underline;\\\">十一</span>响！这排场，唯京官才有！海爷微微闭着眼，低着头，垂着手，腰杆子挺直地跪在地上。身后的家人,有的窃窃私语，有的自言自语，求佛保佑，有的甚至浑身发抖，跪在地上半边身子都斜了。”从这段里的关键词可以看出来，海家人的种种不安的表现是因为没有见过世面，见到京官的大场面害怕。前后文中都没有写“得罪”贺家人的内容。D项 回到原文中检索：“小儿媳鬼精，抢嘴说，是老爷您仁义。”从这两个词可以看出，她是为了讨好海爷。“……小儿媳<span style=\\\"text-decoration: underline;\\\">没弄懂</span>，嘀咕道，不就是<span style=\\\"text-decoration: underline;\\\">没走侧门走正门</span>吗？这有啥啊？”嘀咕表现小儿媳没见识，不是为了讨好海爷。\\n\"}]",
          "questionNo": 1,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550003",
            "name": "理清文章结构及情节",
            "isRight": 1,
            "sons": [{
              "idVo": "785500030008",
              "nameVo": "分析小说情节的方法",
              "basecode": "0177001300030001",
              "isRight": 1,
              "typecode": null
            }]
          }, {
            "id": "78550008",
            "name": "辨别筛选信息",
            "isRight": 1,
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": "0177001300080001",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "分析小说情节的方法",
            "basecodeVo": "0177001300030001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500030008",
              "nameVo": "分析小说情节的方法",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "辨别筛选信息的方法",
            "basecodeVo": "0177001300080001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500080004",
              "nameVo": "辨别筛选信息的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce23f4a0303",
          "answer": "CD",
          "type": "2",
          "score": 4.0,
          "sort": 1,
          "quesId": "8a2a74685a89624f015a8ce23f390302",
          "product": "分析情节及结构安排的方法@辨别筛选信息的方法",
          "productCode": "0177001300030001@0177001300080001",
          "knowledge": "理清文章结构及情节@辨别筛选信息",
          "knowledgeCode": "017700130003@017700130008",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 4.0,
          "surfaceScore": null,
          "stem": "（2）作品中的海爷有哪些性格特点?请简要分析。\n",
          "quesOption": "{\"optionKey\":\"null\",\"optionValue\":\"null\"}",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"检索加工答案信息：文段开头“起初，海爷还是个<span style=\\\"text-decoration: underline;\\\">小油贩子</span>时，”“<span style=\\\"text-decoration: underline;\\\">贺府后来卖给了海爷</span>。因为地势高，地段好，海爷用它做起了油行的门面。”海爷从最初的小油贩子到买下贺府做起油行的生意，说明这个人有经济头脑，善于经营。海爷细心观察贺家人回来祭祖的事儿，观察到不同寻常的一对母子，“贺家有<span style=\\\"text-decoration: underline;\\\">这样的</span>娘儿俩，谁还敢拆他家的祠堂？这么些年了，也不知道那天那个官人，是不是当年那个孩子？”因而不拆祠堂。而且还“海爷吩咐下人，隔些日子把贺家的祠堂打扫干净。到了清明，贺家没人来，海爷还让人烧香点烛，更新一些被老鼠啃坏的牌位。”说明他善于观察，心思缜密，做事有远见。海爷面对京官到来，“海爷微微闭着眼，低着头，垂着手，腰杆子挺直地跪在地上。”而且面对京官的拜谢，“被海爷<span style=\\\"text-decoration: underline;\\\">一把托住</span>。海爷<span style=\\\"text-decoration: underline;\\\">气定神闲</span>地<span style=\\\"text-decoration: underline;\\\">微微一笑</span>，……” 从这几点上可以看出他面对京官并没有在气势上显得很卑微，说明他性格沉稳大气。海爷看到贺府“有个不肖子孙正在卖一只枯瘦的看门狗，海爷不禁喟叹，<span style=\\\"text-decoration: underline;\\\">花无百日红，人无千日好</span>。”后来听到小儿媳的嘀咕，“<span style=\\\"text-decoration: underline;\\\">长叹一声</span>，背着手，回屋去了。”他对于贺家的没落心生感慨，对于海家的将来又隐约担忧，说明他居安思危，考虑长远。\\n\"}]",
          "questionNo": 2,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 1,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550006",
            "name": "分析作品形象，把握人物性格",
            "isRight": 1,
            "sons": [{
              "idVo": "785500060006",
              "nameVo": "概括人物性格特点的方法",
              "basecode": "0177001300060002",
              "isRight": 1,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "概括人物性格特点的方法",
            "basecodeVo": "0177001300060002",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500060006",
              "nameVo": "概括人物性格特点的方法",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce23f4f0304",
          "answer": "（1）有经济头脑，善于经营。海爷最初只是一个小油贩子，最后拥有“银子用斗量”的家产，并买下贺府的豪宅。（2）有长远打算，居安思危。看到贺家不肖子孙卖狗而不禁发出“花无百日红，人无千日好”的感叹；听到小儿媳的嘀咕，长叹一声回到屋里。（3）富有心计，做事果断。由贺家的一对母子来祠堂祭祖的情景，察觉这对母子不同于贺家寻常子孙，于是没有听从别人的建议拆除贺家祠堂，还吩咐下人时常打扫贺家祠堂，事实证明他的决定是正确的。\n",
          "type": "5",
          "score": 4.0,
          "sort": 2,
          "quesId": "8a2a74685a89624f015a8ce23f390302",
          "product": "概括人物性格特点的方法",
          "productCode": "0177001300060002",
          "knowledge": "分析作品形象，把握人物性格",
          "knowledgeCode": "017700130006",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 6.0,
          "surfaceScore": null,
          "stem": "（3）小说为什么以“走正门”为题？有什么好处？\n",
          "quesOption": "{\"optionKey\":\"null\",\"optionValue\":\"null\"}",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"检索加工答案信息：走正门的情节出现在文章的最后一部分，“唯有一个年轻女人,一手拎着篮子，一手领着一个孩子，清早最先来。娘儿俩<span style=\\\"text-decoration: underline;\\\">大大方方</span>地从正门进来，进来后，先将祠堂<span style=\\\"text-decoration: underline;\\\">里里外外擦洗一遍</span>，然后从篮子里拿出一个<span style=\\\"text-decoration: underline;\\\">干净</span>的蒲团，让孩子<span style=\\\"text-decoration: underline;\\\">端端正正</span>地跪拜。拜祭完，<span style=\\\"text-decoration: underline;\\\">整理</span>好衣裳，再<span style=\\\"text-decoration: underline;\\\">昂首阔步地</span>走出去。”从这些词中可以突出贺家母子的堂堂正正，与前文京官回来祭祖的情节形成了呼应。从而突显了主题。同时，上文里说道“其他人来的时候，都<span style=\\\"text-decoration: underline;\\\">跟老鼠似</span>的钻进钻出，拜祭时，有的说说笑笑，有的哭得<span style=\\\"text-decoration: underline;\\\">撕心裂肺</span>，进进出出，都<span style=\\\"text-decoration: underline;\\\">走侧门</span>，怕遇到熟人。”其他人的“走侧门”与“走正门”形成对比。更加突出了这对母子的堂堂正正的形象。\\n\"}]",
          "questionNo": 3,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 1,
          "knowledgeJson": null,
          "tree": [{
            "id": "78550004",
            "name": "概括文章主题及要点",
            "isRight": 1,
            "sons": [{
              "idVo": "785500040007",
              "nameVo": "分析文章标题的作用",
              "basecode": "0177001300040001",
              "isRight": 1,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "分析文章标题的作用",
            "basecodeVo": "0177001300040001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "785500040007",
              "nameVo": "分析文章标题的作用",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce23fce0305",
          "answer": "①贺家年轻母子“走正门”进贺家祠堂祭祖，与贺家其他人“都走侧门，怕遇到熟人”的行为形成鲜明对照，有助于刻画人物形象;②“走正门”的孩子到祠堂祭祖总是“大大方方”“端端正正”“抬头挺胸”“有礼有节”，最终高官得坐，衣锦还乡，从而彰显了小说主题。&nbsp;\n",
          "type": "5",
          "score": 6.0,
          "sort": 3,
          "quesId": "8a2a74685a89624f015a8ce23f390302",
          "product": "分析文章标题作用的方法",
          "productCode": "0177001300040001",
          "knowledge": "概括文章主题及要点",
          "knowledgeCode": "017700130004",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }, {
        "studentGetScore": null,
        "surfaceScore": null,
        "id": "8a2a74685982d902015997cf47b45b61",
        "title": "GYW05543",
        "stem": "阅读下面的文言文，完成后面的问题。\n&nbsp; &nbsp; &nbsp; &nbsp;孙傅，字伯野，海州人，①登进士第，为礼部员外郎。时蔡翛为尚书，傅为言天下事， 劝其亟有所更，不然必败。翛不能用。迁至中书舍人。<span style=\"text-decoration: underline;\">宣和末高丽人入贡使者所过调夫治舟骚然烦费傅言素民力以妨农功而于中国无丝毫之益宰相谓其所论同苏轼奏贬蕲州安置</span>给事中许翰以为傅论议虽偶与轼合，意亦亡他，以职论事而责之过矣，翰亦罢去。靖康元年，召为给事中，进②兵部尚书。上章乞复祖宗法度，③钦宗问之，傅曰：“祖宗法惠民，熙、丰法惠国，崇、观法惠奸。”时谓名言。十一月，拜尚书右丞，俄改同知枢密院。金人围都城，傅日夜亲当矢石，金兵分四翼噪而前，兵败退，坠于护龙河，填尸皆满，城门急闭。是日，金人遂登城。二年正月，钦宗诣金帅营，以傅辅④太子留守，仍兼少傅。帝兼旬不返，傅屡贻书请之。及废立檄至，傅大恸曰：“<span style=\"text-decoration: underline;\">吾唯知吾君可帝中国尔，苟立异姓，吾当死之。</span>”金人来索太上，帝后、诸王、妃主，傅留太子不遣。密谋匿之民间，别求状类宦者二人杀之， 并斩十数死囚，持首送之，紿金人曰：“宦者欲窃太子出，都人争斗杀之，误伤太子。 因帅兵讨定，斩其为乱者以献。苟不已，则以死继之。”越五日，无肯承其事者。傅日： “吾为太子傅，当同生死。<span style=\"text-decoration: underline;\">金人虽不吾索，吾当与之俱行，求见二酋面责之，庶或万一可济。</span>”遂从太子出。金守门者曰：“所欲得太子，留守何预？”傅曰：“我宋之大臣，且太子傅也，当死从。”是夕，宿门下；明日，金人召之去。明年二月，死于朔廷。绍兴中，赠开府仪同三司，谥曰忠定。 （节选自《宋史•孙傅传》）\n",
        "quesOption": "",
        "answer": "",
        "type": "6",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"略\"}]",
        "difficultStar": 2,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": null,
        "productions": "特殊称谓@理解文言实词的含义@如何翻译文言文中的句子@倒装句@概括主要内容及作者观点态度的方法@选出正确断句",
        "productionCode": "01770011000600010014@01770012000300010002@01770012000300030001@01770012000300030003@01770012000300050001@01770012000300060002",
        "score": 19.0,
        "enlargeId": "8a2a7468559088eb015594f5b62800f3",
        "knowledges": "人的称谓@常见文言实词在文中的含义@归纳内容要点，概括主旨大意@断句@理解并翻译文中的句子",
        "costTime": null,
        "sort": 3,
        "questionNo": 4,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": null,
        "list": null,
        "knowledgeJson": null,
        "tree": [],
        "basetree": [],
        "componentQuestions": [{
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（1）下列对文中画线部分的断句，正确的一项是（ &nbsp; ）\n宣和末高丽人入贡使者所过调夫治舟骚然烦费傅言素民力以妨农功而于中国无丝毫之益宰相谓其所论同苏轼奏贬蕲州安置\n",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"宣和末/高丽入贡使者/所过调夫治舟/骚然烦费/傅言/索民力以妨农功/而 于中田无丝毫之益/ 宰相谓其所论/同苏轼奏/贬蕲州安置/\"},{\"optionKey\":\"B\",\"optionValue\":\"宣和末/高丽入贡/使者所过/调夫治舟/骚然烦费/傅言/索民力以妨农功/ 而于中国无丝毫之益/宰相谓其所论/同苏轼奏/贬蕲州安罝/\"},{\"optionKey\":\"C\",\"optionValue\":\"宣和末/高丽入贡/使者所过/调夫治舟/骚然烦费/傅言/索民力以妨农功/ 而于中国无丝毫之益/宰相谓其所论同苏轼/奏贬蕲州安置/\"},{\"optionKey\":\"D\",\"optionValue\":\"宣和末/高丽入贡使者/所过调夫治舟/骚然烦费/傅言/索民力以妨农功/而于中国无丝毫之益/宰相谓其所论同苏轼/奏贬蕲州安罝/\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"“宰相谓其所论同苏轼”意思是：宰相认为他的言论和苏轼相同，所以应该在“苏轼”之后断开，排除AB两项，“使者”是下一句的主语，并不是上一句的宾语，所以应在“高丽入贡”之后断开，因此可以确定答案为C。\"}]",
          "questionNo": 1,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78430006",
            "name": "断句",
            "isRight": 0,
            "sons": [{
              "idVo": "784300060005",
              "nameVo": "选出正确断句",
              "basecode": "01770012000300060002",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "选出正确断句",
            "basecodeVo": "01770012000300060002",
            "typecodeVo": "fangfayunyonglei",
            "sons": [{"idVo": "784300060005", "nameVo": "选出正确断句", "basecode": null, "isRight": 0, "typecode": null}],
            "isTrue": 0
          }],
          "id": "8a2a74685a89624f015a8ce262a20307",
          "answer": "C",
          "type": "1",
          "score": 3.0,
          "sort": 1,
          "quesId": "8a2a74685a89624f015a8ce2628c0306",
          "product": "选出正确断句",
          "productCode": "01770012000300060002",
          "knowledge": "断句",
          "knowledgeCode": "0177001200030006",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（2）下列对文中词语的相关内容的解说,不正确的一项是（ &nbsp; ）\n",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"①登进士第，又可称为进士及第，指科举时代经考试合格后录取成为进士。\"},{\"optionKey\":\"B\",\"optionValue\":\"②兵部是古代“六部”之一，掌管全国武官选用和兵籍、军械、军令等事宜。\"},{\"optionKey\":\"C\",\"optionValue\":\"③庙号是皇帝死后，在太庙立室奉祀时特起的名号，如高祖、太宗、钦宗。\"},{\"optionKey\":\"D\",\"optionValue\":\"④太子指封建时代君主儿子中被确定继承君位的人，有时也可指其他儿子。\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"D项中，“有时也可指其他儿子”错误。古代文学常识需要注意日常积淀，考场上：①检索文化积淀，结合文本解读；②检索选项关键，找出鲜明误点。“太子”一词只指已确定继承皇位或帝位的帝王的儿子。\\n\"}]",
          "questionNo": 2,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78430008",
            "name": "文化常识",
            "isRight": 0,
            "sons": [{
              "idVo": "784300080050",
              "nameVo": "特殊称谓",
              "basecode": "01770011000600010014",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "特殊称谓",
            "basecodeVo": "01770011000600010014",
            "typecodeVo": "shishi(F)",
            "sons": [{"idVo": "784300080050", "nameVo": "特殊称谓", "basecode": null, "isRight": 0, "typecode": null}],
            "isTrue": 0
          }],
          "id": "8a2a74685a89624f015a8ce262a60308",
          "answer": "D",
          "type": "1",
          "score": 3.0,
          "sort": 2,
          "quesId": "8a2a74685a89624f015a8ce2628c0306",
          "product": "特殊称谓",
          "productCode": "01770011000600010014",
          "knowledge": "人的称谓",
          "knowledgeCode": "0177001100060001",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "（3）下列对原文有关内容的概括和分析，不正确的一项是（ &nbsp; ）\n",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"孙傅入仕以后，积极向上建言。他担任礼部员外郎，对尚书蔡脩纵论天下大事，劝蔡迅速有所变更，否则必将失败，可惜他的建议没有被采纳。\"},{\"optionKey\":\"B\",\"optionValue\":\"孙傅不畏金人，努力保全太子。金人掳走钦宗后又索求太子，他密谋藏匿太子，杀二宦官将首级送至金营，欺骗金人说，这就是误伤太子之人。\"},{\"optionKey\":\"C\",\"optionValue\":\"孙傅上奏，请求恢复祖宗法度，他任兵部尚书，从效用角度评价祖宗法度和熙、丰年间的法度，批评崇观年间的法度，受到时人赞许。&nbsp;\"},{\"optionKey\":\"D\",\"optionValue\":\"孙傅舍身取义，死后谥为忠定。太子被迫至金营，孙傅随往，却受到守门者劝阻，他表示身为太子傅，应誓死跟从太子；后被金人召去，死于北廷。\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":null,\"analyzeValue\":\"A.检索相关文句：孙傅，字伯野，海州人，登进士第，为礼部员外郎。时蔡翛为尚书，傅为言天下事， 劝其亟有所更，不然必敗。翛不能用。——检索判断：符合文意。\\nB. 检索相关文句：金人来索太上，帝后、诸王、妃主，傅留太子不遣。密谋匿之民间，别求状类宦者二人杀之， 并斩十数死囚，持首送之，紿金人曰：“宦者欲窃太子出，都人争斗杀之，误伤太子。因帅兵讨定，斩其为乱者以献。苟不已，则以死继之。”——检索判断：不符合文意。（错误点：文句“别求状类宦者二人杀之，并斩十数死囚，持首送之”；杀了两个外貌像宦官的人，不是“杀二宦官”。）\\nC. 检索相关文句：靖康元年，召为给事中，进兵部尚书。上章乞复祖宗法度，钦宗问之，傅曰：“祖宗法惠民，熙、丰法惠国，崇、观法惠奸。”时谓名言。——检索判断：符合文意。\\nD.检索相关文句：遂从太子出。金守门者曰：“所欲得太子，留守何预？”傅曰：“我宋之大臣，且太子傅也，当死从。”是夕，宿门下；明日，金人召之去。明年二月，死于朔廷。绍兴中，赠开府仪同三司，谥曰忠定。——检索判断：符合文意。\\n\"}]",
          "questionNo": 3,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "78430001",
            "name": "常见文言实词在文中的含义",
            "isRight": 0,
            "sons": [{
              "idVo": "784300010005",
              "nameVo": "理解文言实词的含义",
              "basecode": "01770012000300010002",
              "isRight": 0,
              "typecode": null
            }]
          }, {
            "id": "78430005",
            "name": "归纳内容要点，概括主旨大意",
            "isRight": 0,
            "sons": [{
              "idVo": "784300050003",
              "nameVo": "概括主要内容及作者观点态度的方法",
              "basecode": "01770012000300050001",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "理解文言实词的含义",
            "basecodeVo": "01770012000300010002",
            "typecodeVo": "lijielianjiexing",
            "sons": [{
              "idVo": "784300010005",
              "nameVo": "理解文言实词的含义",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 0
          }, {
            "basenameVo": "概括主要内容及作者观点态度的方法",
            "basecodeVo": "01770012000300050001",
            "typecodeVo": "fangfayunyonglei",
            "sons": [{
              "idVo": "784300050003",
              "nameVo": "概括主要内容及作者观点态度的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 0
          }],
          "id": "8a2a74685a89624f015a8ce262ab0309",
          "answer": "B",
          "type": "1",
          "score": 3.0,
          "sort": 3,
          "quesId": "8a2a74685a89624f015a8ce2628c0306",
          "product": "理解实词含义@概括主要内容及作者观点态度的方法",
          "productCode": "01770012000300010002@01770012000300050001",
          "knowledge": "常见文言实词在文中的含义@归纳内容要点，概括主旨大意",
          "knowledgeCode": "0177001200030001@0177001200030005",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 10.0,
          "surfaceScore": null,
          "stem": "（4）把文中画横线的句子翻译成现代汉语。\n①吾唯知吾君可帝中国尔，苟立异姓，吾当死之。\n②金人虽不吾索，吾当与之俱行，求见二酋面责之，庶或万一可济。",
          "quesOption": "{\"optionKey\":\"null\",\"optionValue\":\"null\"}",
          "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"①我只知道我的君王可以在中原称帝而已，如果另立异族的人做皇帝，我将当即为此赴死。\\n<span style=\\\"text-decoration: none;\\\">②</span>金人虽然没有点名索要我，我也应当跟随太子同去，求见两名敌酋首领当面谴责他们的过错，或许可能成功。赋分点：“帝”“死之”“不吾索”“面责”“庶或”“济”。\\n\"}]",
          "questionNo": 4,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 1,
          "knowledgeJson": null,
          "tree": [{
            "id": "78430001",
            "name": "常见文言实词在文中的含义",
            "isRight": 1,
            "sons": [{
              "idVo": "784300010005",
              "nameVo": "理解文言实词的含义",
              "basecode": "01770012000300010002",
              "isRight": 1,
              "typecode": null
            }]
          }, {
            "id": "78430003",
            "name": "理解并翻译文中的句子",
            "isRight": 1,
            "sons": [{
              "idVo": "784300030011",
              "nameVo": "如何翻译文言文中的句子",
              "basecode": "01770012000300030001",
              "isRight": 1,
              "typecode": null
            }, {
              "idVo": "784300030013",
              "nameVo": "倒装句",
              "basecode": "01770012000300030003",
              "isRight": 1,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "理解文言实词的含义",
            "basecodeVo": "01770012000300010002",
            "typecodeVo": "lijielianjiexing",
            "sons": [{
              "idVo": "784300010005",
              "nameVo": "理解文言实词的含义",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "如何翻译文言文中的句子",
            "basecodeVo": "01770012000300030001",
            "typecodeVo": "biaodaxing",
            "sons": [{
              "idVo": "784300030011",
              "nameVo": "如何翻译文言文中的句子",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "倒装句",
            "basecodeVo": "01770012000300030003",
            "typecodeVo": "guize",
            "sons": [{"idVo": "784300030013", "nameVo": "倒装句", "basecode": null, "isRight": 1, "typecode": null}],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce262af030a",
          "answer": "①我只知道我的君王可以在中国称帝而已，如果另立异族，我将为此而死。　\n②金人虽然没有点名要我，我却应该与太子同去，求见两名首领当面指责他们，或许有成功的可能。\n\n",
          "type": "5",
          "score": 10.0,
          "sort": 4,
          "quesId": "8a2a74685a89624f015a8ce2628c0306",
          "product": "理解文言实词的含义@如何翻译文言文中的句子@倒装句",
          "productCode": "01770012000300010002@01770012000300030001@01770012000300030003",
          "knowledge": "常见文言实词在文中的含义@理解并翻译文中的句子",
          "knowledgeCode": "0177001200030001@0177001200030003",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }, {
        "studentGetScore": null,
        "surfaceScore": null,
        "id": "8a2a74685982d902015997d0dc685b62",
        "title": "GYW05544",
        "stem": " 阅读下面这首诗，回答问题。\n\n<p style=\"text-align: center;\"><strong>红 &nbsp;梅</strong></p><p style=\"text-align: center;\">苏轼</p><p style=\"text-align: center;\">怕愁贪睡独开迟，自恐冰容不入时。</p><p style=\"text-align: center;\">故作小红桃杏色，尚余孤瘦雪霜姿。</p><p style=\"text-align: center;\">寒心未肯随春态，酒晕无端上玉肌。</p><p style=\"text-align: center;\">诗老不知梅格在，更看绿叶与青枝。\n\n</p>",
        "quesOption": "",
        "answer": "",
        "type": "6",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"1\"}]",
        "difficultStar": 2,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": null,
        "productions": "鉴赏诗歌意象的方法@莲花的象征意义@梅花的象征意义@把握诗歌情感主旨的方法@理解诗句含义的方法",
        "productionCode": "01770012000200010001@01770012000200010009@01770012000200010010@01770012000200030002@01770012000200060001",
        "score": 11.0,
        "enlargeId": "8a2a7468559088eb015594f5b62800f3",
        "knowledges": "把握诗歌的情感、主旨@理解诗句@鉴赏诗歌的形象",
        "costTime": null,
        "sort": 4,
        "questionNo": 5,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": null,
        "list": null,
        "knowledgeJson": null,
        "tree": [],
        "basetree": [],
        "componentQuestions": [{
          "userAnswerResul": null,
          "studentGetScore": 0.0,
          "surfaceScore": null,
          "stem": "对这首诗的理解，不恰当的两项是（ &nbsp;）\n",
          "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"面对百花盛开的“春态”，红梅仍深自怵惕，保持自己的节操。\\n\"},{\"optionKey\":\"B\",\"optionValue\":\"“尚余”句在写红梅“雪霜姿”的同时，也透露出一丝无奈。\\n\"},{\"optionKey\":\"C\",\"optionValue\":\"“自恐”句不是说自己真的担心，而是含蓄地表达了不愿趋时的情感。\\n\"},{\"optionKey\":\"D\",\"optionValue\":\"“酒晕”句是说梅花之色仿佛是人饮酒后脸上泛起的红晕。\\n\"},{\"optionKey\":\"E\",\"optionValue\":\"诗人使用拟人手法，以红梅自况，表达了与桃杏一起装点春天的愿望。\\n\"}]",
          "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"B项，“‘尚余’句透露出一丝无奈”不正确。“尚余孤瘦雪霜姿”联系上文“自恐冰容不入时”、“故作小红桃杏色”可知，这里的“尚余”是“仍然保留”的意思，不是无奈而是赞赏。是说无论谁人也无法动摇红梅凌霜傲雪的风姿，表现的是一股冷峻、豪迈之气。此项的说法是对作品基本情调的理解失当。\\n E项，“诗人……以红梅自况，表达了与桃杏一起装点春天的愿望”不正确。本诗表达的并非“与桃杏一起装点春天的愿望”，而是诗人使用拟人手法，以红梅自况，表达自己不愿与桃杏一起装点春天，自成一片春光，保持高洁、孤傲的梅格，坚持保持自己的节操。诗中只说红梅的外表颜色与桃花杏花接近，并未表现红梅欲与桃杏争春的意味，况且诗中“怕愁贪睡独开迟”“寒心未肯随春态”等诗句明明白白地道出红梅不愿争春的意味。此项的说法是对作者情感态度的理解、分析失当。\\n\"}]",
          "questionNo": 1,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 0,
          "knowledgeJson": null,
          "tree": [{
            "id": "783900020001",
            "name": "鉴赏诗歌的意象",
            "isRight": 1,
            "sons": [{
              "idVo": "7839000200010024",
              "nameVo": "鉴赏诗歌意象的方法",
              "basecode": "01770012000200010001",
              "isRight": 1,
              "typecode": null
            }, {
              "idVo": "7839000200010033",
              "nameVo": "梅花的象征意义",
              "basecode": "01770012000200010010",
              "isRight": 1,
              "typecode": null
            }]
          }, {
            "id": "783900020008",
            "name": "理解诗句",
            "isRight": 1,
            "sons": [{
              "idVo": "7839000200080001",
              "nameVo": "理解诗句含义的方法",
              "basecode": "01770012000200060001",
              "isRight": 0,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "鉴赏诗歌意象的方法",
            "basecodeVo": "01770012000200010001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "7839000200010024",
              "nameVo": "鉴赏诗歌意象的方法",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "梅花的象征意义",
            "basecodeVo": "01770012000200010010",
            "typecodeVo": "lijielianjiexing",
            "sons": [{
              "idVo": "7839000200010033",
              "nameVo": "梅花的象征意义",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "理解诗句含义的方法",
            "basecodeVo": "01770012000200060001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "7839000200080001",
              "nameVo": "理解诗句含义的方法",
              "basecode": null,
              "isRight": 0,
              "typecode": null
            }],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce28a92030c",
          "answer": "BE",
          "type": "2",
          "score": 4.0,
          "sort": 1,
          "quesId": "8a2a74685a89624f015a8ce28a84030b",
          "product": "理解诗句含义的方法@鉴赏诗歌意象的方法@梅花的象征意义",
          "productCode": "01770012000200060001@01770012000200010001@01770012000200010010",
          "knowledge": "理解诗句@鉴赏诗歌的形象",
          "knowledgeCode": "0177001200020006@0177001200020001",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }, {
          "userAnswerResul": null,
          "studentGetScore": 7.0,
          "surfaceScore": null,
          "stem": "读下面苏轼的诗论并回答问题。\n<span style=\"text-indent: 32px;\"></span><span style=\"text-indent: 32px;\">林逋《梅花》诗云，“疏影横斜水清浅，暗香浮动月黄昏”，决非桃李诗。皮日休《白莲》诗云，“无情有恨何人见，月晓风清欲坠时”，决非红莲诗。此乃写物之功。若石曼卿《红梅》诗云，“认桃无绿叶，辨杏有青枝”，此村学中至陋语也。</span>&nbsp; &nbsp; &nbsp; &nbsp;\n\n结合诗论具体分析苏轼为什么赞扬林诗和皮诗，却批评石诗。\n",
          "quesOption": "[{\"optionKey\":\"\",\"optionValue\":\"\"}]",
          "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"分析题目，找出苏轼赞扬写梅花、白莲的理由。\\n林诗中写梅“<span style=\\\"text-decoration: underline;\\\">疏</span>影横斜水清浅，<span style=\\\"text-decoration: underline;\\\">暗</span>香浮动月黄昏”，苏轼评论他“非桃李诗”，因为“疏”“暗”两个字写出了梅的清幽、高洁，不做作，不刻意，梅花象征着高洁、自爱的情操。\\n皮诗写白莲，“无情有恨<span style=\\\"text-decoration: underline;\\\">何人见</span>，<span style=\\\"text-decoration: underline;\\\">月晓风清</span>欲坠时”，写出了白莲的多情，和不愿人打扰的高洁。\\n接着从石曼卿的诗句内容中找出苏轼批评他的理由。\\n石曼卿写梅“认桃无<span style=\\\"text-decoration: underline;\\\">绿叶</span>，辩杏有<span style=\\\"text-decoration: underline;\\\">青枝</span>”，仅从“绿叶”、“青枝”等外形上把握红梅的特征，未见红梅的精神品格。“青枝”“绿叶”都只是写出了梅的表象，没有突出它的象征意义。\"}]",
          "questionNo": 2,
          "questionAudio": null,
          "isFavorite": 0,
          "isImg": null,
          "isComplex": null,
          "answerRecordCode": null,
          "baseProductionJson": null,
          "markQuestionResult": 1,
          "knowledgeJson": null,
          "tree": [{
            "id": "783900020001",
            "name": "鉴赏诗歌的意象",
            "isRight": 1,
            "sons": [{
              "idVo": "7839000200010024",
              "nameVo": "鉴赏诗歌意象的方法",
              "basecode": "01770012000200010001",
              "isRight": 1,
              "typecode": null
            }, {
              "idVo": "7839000200010032",
              "nameVo": "莲花的象征意义",
              "basecode": "01770012000200010009",
              "isRight": 1,
              "typecode": null
            }, {
              "idVo": "7839000200010033",
              "nameVo": "梅花的象征意义",
              "basecode": "01770012000200010010",
              "isRight": 1,
              "typecode": null
            }]
          }, {
            "id": "783900020004",
            "name": "把握诗歌情感、主旨",
            "isRight": 1,
            "sons": [{
              "idVo": "7839000200040013",
              "nameVo": "把握诗歌情感主旨的方法",
              "basecode": "01770012000200030002",
              "isRight": 1,
              "typecode": null
            }]
          }],
          "basetree": [{
            "basenameVo": "鉴赏诗歌意象的方法",
            "basecodeVo": "01770012000200010001",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "7839000200010024",
              "nameVo": "鉴赏诗歌意象的方法",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "莲花的象征意义",
            "basecodeVo": "01770012000200010009",
            "typecodeVo": "lijielianjiexing",
            "sons": [{
              "idVo": "7839000200010032",
              "nameVo": "莲花的象征意义",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "梅花的象征意义",
            "basecodeVo": "01770012000200010010",
            "typecodeVo": "lijielianjiexing",
            "sons": [{
              "idVo": "7839000200010033",
              "nameVo": "梅花的象征意义",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }, {
            "basenameVo": "把握诗歌情感主旨的方法",
            "basecodeVo": "01770012000200030002",
            "typecodeVo": "fangfafenxilei",
            "sons": [{
              "idVo": "7839000200040013",
              "nameVo": "把握诗歌情感主旨的方法",
              "basecode": null,
              "isRight": 1,
              "typecode": null
            }],
            "isTrue": 1
          }],
          "id": "8a2a74685a89624f015a8ce28a98030d",
          "answer": "苏轼赞扬的理由是，写梅花、白莲的诗能做到神似，表现了神韵、精神品格、内在特点；批评的理由是，石曼卿的《红梅》诗不能抓住梅花的品格特征，仅作了外形描写。\n具体分析：\n①“疏影横斜水清浅，暗香浮动月黄昏”，“疏”“暗”两个字写出了梅的清幽、高洁，不做作，不刻意；\n②“无情有恨何人见，月晓风清欲坠时”，写出了白莲的多情，和不愿人打扰的高洁；\n③“认桃无绿叶，辩杏有青枝”，仅从“绿叶”“青枝”等外形上把握红梅的特征，未见红梅的精神品格。\n",
          "type": "5",
          "score": 7.0,
          "sort": 2,
          "quesId": "8a2a74685a89624f015a8ce28a84030b",
          "product": "鉴赏诗歌意象的方法@莲花的象征意义@梅花的象征意义@把握诗歌情感主旨的方法",
          "productCode": "01770012000200010001@01770012000200010009@01770012000200010010@01770012000200030002",
          "knowledge": "鉴赏诗歌的形象@把握诗歌的情感、主旨",
          "knowledgeCode": "0177001200020001@0177001200020003",
          "subjectCode": "1",
          "voice": "",
          "godpenAnswer": null
        }],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }],
      "itemContent": "阅读",
      "itemType": "6",
      "enlargeType": null,
      "itemScore": 56.0,
      "sort": 2,
      "logicType": "q_605"
    }]
  }, {
    "type": "4",
    "typeList": [{
      "id": "8a2a74685a89624f015a8ce0b11d02ed",
      "list": [{
        "studentGetScore": 5.0,
        "surfaceScore": null,
        "id": "8a2a74685920e2f0015925aa48b70526",
        "title": "GYW05504",
        "stem": "补写出下列句子中的空缺部分。\n（1）李白《蜀道难》中“________，_______”两句写山势高险，即便是善飞的黄鹤、轻捷的猿猴都很难越过。\n（2）荀子认为人性本“恶”，且认为后天学习可以改造人，因此他的《劝学》并非一般意义上的劝勉人们学习文化知识，而是劝人为“善”，文中“_______，______，______”可见。",
        "quesOption": "",
        "answer": "[{\"answerValue\":\"黄鹤之飞尚不得过\",\"score\":\"1\"},{\"answerValue\":\"猿猱欲度愁攀援\",\"score\":\"1\"},{\"answerValue\":\"积善成德\",\"score\":\"1\"},{\"answerValue\":\"而神明自得\",\"score\":\"1\"},{\"answerValue\":\"圣心备焉\",\"score\":\"1\"}]",
        "type": "4",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"（1）黄鹤之飞尚不得过，猿猱欲度愁攀援。\\n（2）积善成德，而神明自得，圣心备焉。\"}]",
        "difficultStar": 1,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": "http://cuotiben-mp3.qiniudn.com/GYW05504.mp3",
        "productions": "《劝学》@古文的情境默写@《蜀道难》@古诗的情境默写",
        "productionCode": "01770012000100010005@01770012000100010024@01770012000100020024@01770012000100020030",
        "score": 5.0,
        "enlargeId": "402881b45194ffbc01519510d7760011",
        "knowledges": "古文填空@古诗填空",
        "costTime": null,
        "sort": 1,
        "questionNo": 6,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": 1,
        "list": null,
        "knowledgeJson": null,
        "tree": [{
          "id": "783900010001",
          "name": "古文填空",
          "isRight": 1,
          "sons": [{
            "idVo": "7839000100010026",
            "nameVo": "《劝学》",
            "basecode": "01770012000100010005",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "7839000100010042",
            "nameVo": "古文的情境默写",
            "basecode": "01770012000100010024",
            "isRight": 1,
            "typecode": null
          }]
        }, {
          "id": "783900010002",
          "name": "古诗填空",
          "isRight": 1,
          "sons": [{
            "idVo": "7839000100020050",
            "nameVo": "《蜀道难》",
            "basecode": "01770012000100020024",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "7839000100020052",
            "nameVo": "古诗的情境默写",
            "basecode": "01770012000100020030",
            "isRight": 1,
            "typecode": null
          }]
        }],
        "basetree": [{
          "basenameVo": "《劝学》",
          "basecodeVo": "01770012000100010005",
          "typecodeVo": "lianjiexing",
          "sons": [{"idVo": "7839000100010026", "nameVo": "《劝学》", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "古文的情境默写",
          "basecodeVo": "01770012000100010024",
          "typecodeVo": "lijielianjiexing",
          "sons": [{
            "idVo": "7839000100010042",
            "nameVo": "古文的情境默写",
            "basecode": null,
            "isRight": 1,
            "typecode": null
          }],
          "isTrue": 1
        }, {
          "basenameVo": "《蜀道难》",
          "basecodeVo": "01770012000100020024",
          "typecodeVo": "lianjiexing",
          "sons": [{"idVo": "7839000100020050", "nameVo": "《蜀道难》", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "古诗的情境默写",
          "basecodeVo": "01770012000100020030",
          "typecodeVo": "lijielianjiexing",
          "sons": [{
            "idVo": "7839000100020052",
            "nameVo": "古诗的情境默写",
            "basecode": null,
            "isRight": 1,
            "typecode": null
          }],
          "isTrue": 1
        }],
        "componentQuestions": [],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }],
      "itemContent": "填空题",
      "itemType": "4",
      "enlargeType": null,
      "itemScore": 5.0,
      "sort": 3,
      "logicType": "q_400"
    }]
  }, {
    "type": "1",
    "typeList": [{
      "id": "8a2a74685a89624f015a8ce0e15202ee",
      "list": [{
        "studentGetScore": 0.0,
        "surfaceScore": null,
        "id": "8a2a7468593fc45e015949268f1953a8",
        "title": "GYW05535",
        "stem": "下列各句中加点词语的使用，全都正确的一项是（ &nbsp;）\n①碳排放过量会给地球生态环境带来严重的危害，如果不设法加以遏制，必然会威胁人类生存，全球性大灾难<span style=\"text-decoration: underline;\">指日可待</span>。\n②出色的庄稼汉，干练的机械师，枪法如神的士兵，<span style=\"text-decoration: underline;\">妙笔生花</span>的作家，他们都值得我们敬佩。\n③泰山几千年来都是文人墨客们向往的圣地，在<span style=\"text-decoration: underline;\">浩如烟海</span><span style=\"text-decoration: none;\">的中华典籍中，留下了众多颂扬泰山的诗词文章。\n④这位姑娘天生就眼睛深凹，鼻梁挺直，头发卷曲，身材苗条，好似</span><span style=\"text-decoration: underline;\">芝兰玉树</span><span style=\"text-decoration: none;\">，在黄皮肤黑眼睛的国度里，很容易被人认出。\n⑤家庭条件的优越和父母的溺爱，养成了他傲慢狂妄的个性，不管对谁都</span><span style=\"text-decoration: underline;\">侧目而视</span><span style=\"text-decoration: none;\">，一副天不怕地不怕的小霸王样子。\n⑥张先生在这所大学从事教学和研究工作三十余年，学问炉火纯青，性格</span><span style=\"text-decoration: underline;\">外圆内方</span><span style=\"text-decoration: none;\">，所以既受尊重，又有很多朋友。</span>",
        "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"①③⑤\"},{\"optionKey\":\"B\",\"optionValue\":\"③④⑥\"},{\"optionKey\":\"C\",\"optionValue\":\"②③⑥\"},{\"optionKey\":\"D\",\"optionValue\":\"②④⑤\"}]",
        "answer": "C",
        "type": "1",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"①指日可待：（事情、希望等）不久就可以实现。（词语对象：希望。感情色彩：褒义）语境判断依据：灾难。语境对象和色彩都与“指日可待”不匹配，使用不恰当。答案信息只有一个词语“灾难”，其余都是干扰信息。\\n②妙笔生花：形容文笔好，善于写作。（词语对象：写作。感情色彩：褒义。）语境判断依据：作家。恰当。无误点。\\n③浩如烟海：形容文献、资料等非常丰富。（词语对象：文献、资料等。感情色彩：褒义）语境判断依据：典籍。恰当。无误点。\\n④芝兰玉树：本比喻高尚人的子弟，后亦用作对优秀子弟的美称。（词语对象：子弟。感情色彩：褒义）语境判断依据：姑娘。不恰当。\\n⑤侧目而视：形容畏惧或愤恨不满的神情。（词语对象：畏惧。感情色彩：贬义）语境判断依据：小霸王。不恰当。\\n⑥外圆内方：指人外表随和，内心却很严正。（词语对象：人。感情色彩：褒义）语境判断依据：性格。恰当。无误点。\\n\"}]",
        "difficultStar": 2,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": "http://cuotiben-mp3.qiniudn.com/GYW05535.mp3",
        "productions": "理解词语的含义@判断词语适用对象的方法@判断词语适用感情色彩的方法",
        "productionCode": "01770010000200030001@01770010000200030002@01770010000200030003",
        "score": 3.0,
        "enlargeId": "402881b951dd6d230151dd8cf375000c",
        "knowledges": "词语使用",
        "costTime": null,
        "sort": 1,
        "questionNo": 7,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": 0,
        "list": null,
        "knowledgeJson": null,
        "tree": [{
          "id": "779600020001",
          "name": "词语使用",
          "isRight": 0,
          "sons": [{
            "idVo": "7796000200010011",
            "nameVo": "理解词语的含义",
            "basecode": "01770010000200030001",
            "isRight": 0,
            "typecode": null
          }, {
            "idVo": "7796000200010012",
            "nameVo": "判断词语的适用对象",
            "basecode": "01770010000200030002",
            "isRight": 0,
            "typecode": null
          }, {
            "idVo": "7796000200010013",
            "nameVo": "判断词语适用的感情色彩",
            "basecode": "01770010000200030003",
            "isRight": 0,
            "typecode": null
          }]
        }],
        "basetree": [{
          "basenameVo": "理解词语的含义",
          "basecodeVo": "01770010000200030001",
          "typecodeVo": "lijielianjiexing",
          "sons": [{
            "idVo": "7796000200010011",
            "nameVo": "理解词语的含义",
            "basecode": null,
            "isRight": 0,
            "typecode": null
          }],
          "isTrue": 0
        }, {
          "basenameVo": "判断词语的适用对象",
          "basecodeVo": "01770010000200030002",
          "typecodeVo": "lijielianjiexing",
          "sons": [{
            "idVo": "7796000200010012",
            "nameVo": "判断词语的适用对象",
            "basecode": null,
            "isRight": 0,
            "typecode": null
          }],
          "isTrue": 0
        }, {
          "basenameVo": "判断词语适用的感情色彩",
          "basecodeVo": "01770010000200030003",
          "typecodeVo": "lijielianjiexing",
          "sons": [{
            "idVo": "7796000200010013",
            "nameVo": "判断词语适用的感情色彩",
            "basecode": null,
            "isRight": 0,
            "typecode": null
          }],
          "isTrue": 0
        }],
        "componentQuestions": [],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }, {
        "studentGetScore": 0.0,
        "surfaceScore": null,
        "id": "8a2a74685982d902015997c191c45b5d",
        "title": "GYW05547",
        "stem": "下列各句中，没有语病的一句是(　　)\n",
        "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"此次《环境保护法》修订，历时两年，前后经过了多次审议，如今终于定稿，在环境先于经济的原则上已达成一致并写入法律。\"},{\"optionKey\":\"B\",\"optionValue\":\"英国曼彻斯特大学的两俄裔学者在获得诺贝尔物理奖后，俄罗斯总统当天批评俄政府没有在年轻学者毕业时为他们提供有吸引力的条件，导致人才流失。\"},{\"optionKey\":\"C\",\"optionValue\":\"随着我国经济的发展，经历了以出口拉动为主导、以投资拉动为主导以及以消费拉动为主导的经济模式的转型过程。\"},{\"optionKey\":\"D\",\"optionValue\":\"《财富》经济论坛最终选址成都，是因为成都具有巨大的经济发展潜力、强大的创新能力、独特的文化气质、丰富的国际会议承办经验以及优良的政务服务等优越条件。\\n\"}]",
        "answer": "D",
        "type": "1",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"A项，默读，提出阻隔内容，“此次《环境保护法》修订，历时两年，前后经过了多次审议”“在环境先于经济的原则上”，没有语病，跳过。剩下“终于定稿”“达成一致”“写入法律”应是：“达成一致”——“终于定稿”——“写入法律”。\\n\\nB项，默读，提取阻隔内容，“英国曼彻斯特大学的两俄裔学者”，没有语病，跳过，“获得诺贝尔物理奖”“俄政府没有在年轻学者毕业时为他们提供有吸引力的条件”，没有语病，跳过。默读整个句子，前面主语是“英国曼彻斯特大学的两俄裔学者”，后面是“俄罗斯总统”，主语不一致，应将“英国曼彻斯特大学的两俄裔学者”移至“在”后面。\\n\\nC项，默读，提取阻隔内容，“以出口拉动为主导、以投资拉动为主导以及以消费拉动为主导的”“经济模式的”，没有语病。提取剩下的内容的主干“随着……，经历了过程”，主语残缺，把“随着”去掉。&nbsp;&nbsp;&nbsp;&nbsp;\\n&nbsp;&nbsp;&nbsp;&nbsp;\\nD项，默读，提取阻隔内容，“巨大的经济发展潜力、强大的创新能力、独特的文化气质、丰富的国际会议承办经验以及优良的政务服务”，没有语病，提取剩下的内容的主干“论坛选址成都，是因为优越条件”，没有语病。\\n\"}]",
        "difficultStar": 2,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": null,
        "productions": "主语残缺@暗换主语@不合事理",
        "productionCode": "01770010000300010001@01770010000300040004@01770010000300050001",
        "score": 3.0,
        "enlargeId": "402881b951dd6d230151dd8cf375000c",
        "knowledges": "成分残缺或赘余@结构混乱@不合逻辑",
        "costTime": null,
        "sort": 2,
        "questionNo": 8,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": 0,
        "list": null,
        "knowledgeJson": null,
        "tree": [{
          "id": "779600030001",
          "name": "成分残缺或赘余",
          "isRight": 0,
          "sons": [{
            "idVo": "7796000300010013",
            "nameVo": "主语残缺",
            "basecode": "01770010000300010001",
            "isRight": 0,
            "typecode": null
          }]
        }, {
          "id": "779600030004",
          "name": "结构混乱",
          "isRight": 0,
          "sons": [{
            "idVo": "7796000300040012",
            "nameVo": "暗换主语",
            "basecode": "01770010000300040004",
            "isRight": 0,
            "typecode": null
          }]
        }, {
          "id": "779600030005",
          "name": "不合逻辑",
          "isRight": 0,
          "sons": [{
            "idVo": "7796000300050011",
            "nameVo": "不合事理",
            "basecode": "01770010000300050001",
            "isRight": 0,
            "typecode": null
          }]
        }],
        "basetree": [{
          "basenameVo": "主语残缺",
          "basecodeVo": "01770010000300010001",
          "typecodeVo": "guize",
          "sons": [{"idVo": "7796000300010013", "nameVo": "主语残缺", "basecode": null, "isRight": 0, "typecode": null}],
          "isTrue": 0
        }, {
          "basenameVo": "暗换主语",
          "basecodeVo": "01770010000300040004",
          "typecodeVo": "guize",
          "sons": [{"idVo": "7796000300040012", "nameVo": "暗换主语", "basecode": null, "isRight": 0, "typecode": null}],
          "isTrue": 0
        }, {
          "basenameVo": "不合事理",
          "basecodeVo": "01770010000300050001",
          "typecodeVo": "guize",
          "sons": [{"idVo": "7796000300050011", "nameVo": "不合事理", "basecode": null, "isRight": 0, "typecode": null}],
          "isTrue": 0
        }],
        "componentQuestions": [],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }, {
        "studentGetScore": 0.0,
        "surfaceScore": null,
        "id": "8a2a7468593fc45e01594477a0bf44e9",
        "title": "GYW05532",
        "stem": "把下列句子组成语意连贯的语段，排序最恰当的一项是(　　)\n①随着文学概念的演变和文学体裁的发展，散文的概念也时有变化。\n②现代散文是指除小说、诗歌、戏剧等文学体裁之外的其他文学作品。\n③其本身按其内容和形式的不同，又可分为杂文、小品、随笔等。散文形散而神不散，有一个明确的主旨贯穿全文。\n④散文是指以文字为创作、审美对象的文学艺术体裁，是文学中的一种体裁形式。\n⑤在某些历史时期又将小说与其他抒情、记事的文学作品统称为散文，以区别于讲求韵律的诗歌。\n⑥六朝以来，为区别于韵文、骈文，而把凡是不押韵、不重排偶的散体文章，概称散文。　\n",
        "quesOption": "[{\"optionKey\":\"A\",\"optionValue\":\"⑥③⑤④①② \"},{\"optionKey\":\"B\",\"optionValue\":\"③②①⑥⑤④\"},{\"optionKey\":\"C\",\"optionValue\":\"④⑥①⑤②③ \"},{\"optionKey\":\"D\",\"optionValue\":\"⑥⑤④①②③\\n\"}]",
        "answer": "C",
        "type": "1",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"一共六句，检索句中信息，对句子进行归类。六句话说的都是散文，检索④句“散文是指……”，为总说散文的概念。第⑥句“六朝以来……概称散文”，说散文概念的来源。检索得出①⑤句信息，“散文的概念也时有变化”，“在某些历史时期……统称为散文”，说散文概念的变化。②③句，“现代散文是指……”“其本身……又可分为……”，讲现代散文的概念。将六句按时间顺序排序，④为总说，放在第一句，⑥为古代，②③为现代，⑥在②③前，中间应该是由古代到现代的变化，为①⑤句。所以正确答案为④⑥①⑤②③。\"}]",
        "difficultStar": 2,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": "http://cuotiben-mp3.qiniudn.com/GYW05532.mp3",
        "productions": "判断语言连贯的方法",
        "productionCode": "01770010000600020001",
        "score": 3.0,
        "enlargeId": "402881b951dd6d230151dd8cf375000c",
        "knowledges": "语言表达的连贯性",
        "costTime": null,
        "sort": 3,
        "questionNo": 9,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": 0,
        "list": null,
        "knowledgeJson": null,
        "tree": [{
          "id": "779600040001",
          "name": "语言表达的连贯性",
          "isRight": 0,
          "sons": [{
            "idVo": "7796000400010004",
            "nameVo": "判断语言连贯的方法",
            "basecode": "01770010000600020001",
            "isRight": 0,
            "typecode": null
          }]
        }],
        "basetree": [{
          "basenameVo": "判断语言连贯的方法",
          "basecodeVo": "01770010000600020001",
          "typecodeVo": "fangfayunyonglei",
          "sons": [{
            "idVo": "7796000400010004",
            "nameVo": "判断语言连贯的方法",
            "basecode": null,
            "isRight": 0,
            "typecode": null
          }],
          "isTrue": 0
        }],
        "componentQuestions": [],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }],
      "itemContent": "单选题",
      "itemType": "1",
      "enlargeType": null,
      "itemScore": 9.0,
      "sort": 4,
      "logicType": "q_100"
    }]
  }, {
    "type": "5",
    "typeList": [{
      "id": "8a2a74685a89624f015a8cea5b4f033c",
      "list": [{
        "studentGetScore": 5.0,
        "surfaceScore": null,
        "id": "8a2a74685920e2f001592981679f0893",
        "title": "GYW05509",
        "stem": "在下面一段文字横线处补写恰当的语句，使整段文字语意完整连贯，内容贴切，逻辑严密。每处不超过10个字。\n&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; 一提到根的作用，可能首先想到<span style=\"text-decoration: underline;\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ① &nbsp; &nbsp; &nbsp; &nbsp;</span>，这两项是绝大多数植物根系的本职工作。 然而，进化史上最早出现的根，作用却并非吸收水分和吸取养料，而是&nbsp;<span style=\"text-decoration: underline;\">&nbsp; &nbsp; &nbsp; &nbsp; ② &nbsp; &nbsp; &nbsp;&nbsp;</span>，这种早期类型的根被称为假根，<span style=\"text-decoration: underline;\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;③ &nbsp; &nbsp; &nbsp;&nbsp;</span>&nbsp;，是因为这些根内没有运输水分和养料的通道，它仅有的作用就是固定植株. 假根将植物固定在合适的生活环境中，会降低风吹和水流的影响，提高其生存几率。\n\n",
        "quesOption": "",
        "answer": "①吸收水分和吸取养料\n②将植株固定在适当环境\n③之所以被称为“假根”",
        "type": "5",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"语段话题：根的作用。\\n①在第一句结尾处，第二句开头“这两项”即指代①的内容。可见，“作用”和“两项”是检索答案信息的路标。据此可知，①处的答案信息是“吸收水分和吸收养料”。\\n同样根据“作用”的指引，检索②处的答案信息是第四句的“固定植株”。再经由“固定”的指引，检索第五句的进一步解说，这应该是更完整的答案信息：“将植物固定在合适的生活环境中”。\\n③承接上句结尾“假根”，提领下文“是因为……”表述的原因，可知③应该是一个设问句“为什么称为‘假根’？”但语段中③后面是逗号，这就要求把设问句式变换为陈述句式。\"}]",
        "difficultStar": 3,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": "http://cuotiben-mp3.qiniudn.com/GYW05509.mp3",
        "productions": "如何连贯地表达语言",
        "productionCode": "01770010000600020002",
        "score": 5.0,
        "enlargeId": "402881c553403dbd015340862a660005",
        "knowledges": "语言表达的连贯性",
        "costTime": null,
        "sort": 1,
        "questionNo": 10,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": 1,
        "list": null,
        "knowledgeJson": null,
        "tree": [{
          "id": "779600040001",
          "name": "语言表达的连贯性",
          "isRight": 1,
          "sons": [{
            "idVo": "7796000400010005",
            "nameVo": "如何连贯地表达语言",
            "basecode": "01770010000600020002",
            "isRight": 1,
            "typecode": null
          }]
        }],
        "basetree": [{
          "basenameVo": "如何连贯地表达语言",
          "basecodeVo": "01770010000600020002",
          "typecodeVo": "biaodaxing",
          "sons": [{
            "idVo": "7796000400010005",
            "nameVo": "如何连贯地表达语言",
            "basecode": null,
            "isRight": 1,
            "typecode": null
          }],
          "isTrue": 1
        }],
        "componentQuestions": [],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }, {
        "studentGetScore": 6.0,
        "surfaceScore": null,
        "id": "8a2a7468593fc45e015944907f164606",
        "title": "GYW05533",
        "stem": "阅读下面的漫画，完成题目。\nhttp://iwrong.b0.upaiyun.com/20161228/14829137119628222.png\n孔子：你们都毕业了，怎么又回来了？\n弟子：外面就业太难，我们回来读研。\n这幅漫画意在讽刺当今一种怎样的现实？请比较古代儒家教育与今天的教育，谈谈你的看法。\n要求：观点鲜明，运用对比论证，100字左右。\n",
        "quesOption": "",
        "answer": "儒家教育，以修身为核心，以治国平天下为目标，学习内容比较单纯。现在教育功利性比较强，学习内容繁杂，读书人多以赚钱发财为目的。现在一些读书人适应社会的能力差，常采取逃避现实的做法。",
        "type": "5",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"此题解答的重点在于概括古今教育的不同，用简明的语言指出今天毕业生就业的现状。结合古代“儒家教育”，采用对比的手法说出古今教育的不同点，并指出漫画讽刺的现象。注意在表达时要观点明确，不能模棱两可。\\n\\n\\n\"}]",
        "difficultStar": 3,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": "http://cuotiben-mp3.qiniudn.com/GYW05533.mp3",
        "productions": "如何用文字表达图片中的信息",
        "productionCode": "01770010000700020001",
        "score": 6.0,
        "enlargeId": "402881c553403dbd015340862a660005",
        "knowledges": "图片转换成文字",
        "costTime": null,
        "sort": 2,
        "questionNo": 11,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": 1,
        "list": null,
        "knowledgeJson": null,
        "tree": [{
          "id": "779600080002",
          "name": "图片转换成文字",
          "isRight": 1,
          "sons": [{
            "idVo": "7796000800020003",
            "nameVo": "如何用文字表达图片中的信息",
            "basecode": "01770010000700020001",
            "isRight": 1,
            "typecode": null
          }]
        }],
        "basetree": [{
          "basenameVo": "如何用文字表达图片中的信息",
          "basecodeVo": "01770010000700020001",
          "typecodeVo": "biaodaxing",
          "sons": [{
            "idVo": "7796000800020003",
            "nameVo": "如何用文字表达图片中的信息",
            "basecode": null,
            "isRight": 1,
            "typecode": null
          }],
          "isTrue": 1
        }],
        "componentQuestions": [],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }],
      "itemContent": "主观题",
      "itemType": "5",
      "enlargeType": null,
      "itemScore": 11.0,
      "sort": 5,
      "logicType": "q_500"
    }, {
      "id": "8a2a74685a89624f015a8cea9ef6033e",
      "list": [{
        "studentGetScore": 60.0,
        "surfaceScore": null,
        "id": "8a2a74685982d902015997bcd1435b52",
        "title": "GYW05551",
        "stem": "阅读下面的材料，根据要求写作文。　　\n \n &nbsp; &nbsp; &nbsp; 运动中的赛跑，是在有限的路程内看你使用了多少时间；人生中的赛跑，是在有限的时间内看你跑了多少路程（冯骥才）&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n请根据上面的材料，自选角度，自拟题目，写一篇不少于800字的记叙文或议论文。\n",
        "quesOption": "",
        "answer": "略",
        "type": "5",
        "quesAnalyze": "[{\"analyzeKey\":\"\",\"analyzeValue\":\"一句话材料，两个分句，通过运动赛跑与人生赛跑的差异，揭示人生的真谛。但是这是大体上的揭示而已。细究之下，仍能浮想联翩。表面看来，运动赛跑与人生赛跑从追求目标和评价标准看，有差异；实质上看，二者都是速度、体能与精神、心理的竞争，又是相同的。更何况，认为运动中的赛跑，都是“在有限的路程内看你使用了多少时间”也是片面的。有些赛跑，就是限定时间，丈量路程。足球运动员的体能测试就有一项“12分钟跑”；专项赛跑，也有限时竞逐的项目。认为人生赛跑，都是“在有限的时间内看你跑了多少路程”也简单化了。为达到某项既定目标，某种工作任务，某个厂商订单，甚至自己近期或者远期的人生规划，也是要争分夺秒的。人们常说，和生命赛跑——真的，二者是分不清也分不开的。\\n\\n写作题目对生活的反映如下图示意：\\nhttp://iwrong.b0.upaiyun.com/2017113/14843121700606849.png\\n题目实质的核心立意：世界是千变万化的，疑问是层出不穷的，答案是丰富多彩的。\\n\"}]",
        "difficultStar": 3,
        "videoPath": null,
        "audioListenPath": null,
        "stageCode": "3",
        "subjectName": "语文",
        "gradeCode": "33",
        "audioAnalyzePath": null,
        "productions": "符合题意@符合文体要求@感情真挚，思想健康@内容充实，中心明确@标点正确，不写错别字@深刻@丰富@有文采@有创新@写作的策略",
        "productionCode": "01770014000400010001@01770014000400010002@01770014000400010003@01770014000400010004@01770014000400010005@01770014000400020001@01770014000400020002@01770014000400020003@01770014000400020004@0177001400050001",
        "score": 60.0,
        "enlargeId": "402881b45194ffbc01519511f9aa0014",
        "knowledges": "基础等级@发展等级@写作的策略",
        "costTime": null,
        "sort": 1,
        "questionNo": 12,
        "userAnswerResul": null,
        "questionAudio": null,
        "isFavorite": 0,
        "isImg": null,
        "isComplex": null,
        "answerRecordCode": null,
        "componentQuestionCode": null,
        "markQuestionResult": 1,
        "list": null,
        "knowledgeJson": null,
        "tree": [{
          "id": "85840006",
          "name": "写作的策略",
          "isRight": 1,
          "sons": [{
            "idVo": "858400060012",
            "nameVo": "符合题意",
            "basecode": "01770014000400010001",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060013",
            "nameVo": "符合文体要求",
            "basecode": "01770014000400010002",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060014",
            "nameVo": "感情真挚，思想健康",
            "basecode": "01770014000400010003",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060015",
            "nameVo": "内容充实，中心明确",
            "basecode": "01770014000400010004",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060016",
            "nameVo": "标点正确，不写错别字",
            "basecode": "01770014000400010005",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060017",
            "nameVo": "深刻",
            "basecode": "01770014000400020001",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060018",
            "nameVo": "丰富",
            "basecode": "01770014000400020002",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060019",
            "nameVo": "有文采",
            "basecode": "01770014000400020003",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060020",
            "nameVo": "有创新",
            "basecode": "01770014000400020004",
            "isRight": 1,
            "typecode": null
          }, {
            "idVo": "858400060011",
            "nameVo": "写作的策略",
            "basecode": "0177001400050001",
            "isRight": 1,
            "typecode": null
          }]
        }],
        "basetree": [{
          "basenameVo": "符合题意",
          "basecodeVo": "01770014000400010001",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060012", "nameVo": "符合题意", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "符合文体要求",
          "basecodeVo": "01770014000400010002",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060013", "nameVo": "符合文体要求", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "感情真挚，思想健康",
          "basecodeVo": "01770014000400010003",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060014", "nameVo": "感情真挚，思想健康", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "内容充实，中心明确",
          "basecodeVo": "01770014000400010004",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060015", "nameVo": "内容充实，中心明确", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "标点正确，不写错别字",
          "basecodeVo": "01770014000400010005",
          "typecodeVo": "celve(S)",
          "sons": [{
            "idVo": "858400060016",
            "nameVo": "标点正确，不写错别字",
            "basecode": null,
            "isRight": 1,
            "typecode": null
          }],
          "isTrue": 1
        }, {
          "basenameVo": "深刻",
          "basecodeVo": "01770014000400020001",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060017", "nameVo": "深刻", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "丰富",
          "basecodeVo": "01770014000400020002",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060018", "nameVo": "丰富", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "有文采",
          "basecodeVo": "01770014000400020003",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060019", "nameVo": "有文采", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "有创新",
          "basecodeVo": "01770014000400020004",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060020", "nameVo": "有创新", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }, {
          "basenameVo": "写作的策略",
          "basecodeVo": "0177001400050001",
          "typecodeVo": "celve(S)",
          "sons": [{"idVo": "858400060011", "nameVo": "写作的策略", "basecode": null, "isRight": 1, "typecode": null}],
          "isTrue": 1
        }],
        "componentQuestions": [],
        "baseProductionJson": null,
        "logicType": null,
        "godpenAnswer": null
      }],
      "itemContent": "话题作文",
      "itemType": "5",
      "enlargeType": null,
      "itemScore": 60.0,
      "sort": 6,
      "logicType": "q_511"
    }]
  }],
  "paperName": "高考语文名家深度诊断（全国卷）170302",
  "subjectCode": "1",
  "gradeCode": "33",
  "type": "专家深度诊断测试卷",
  "booktype": "7HCcMZTzpcThi6RaByWysKQPPbtTHSj8",
  "paperDesc": null,
  "releaseFlag": "1",
  "totalScore": 150.0,
  "totalTime": 150,
  "areaCode": "100000",
  "schoolYear": null,
  "createBy": null,
  "createName": null,
  "updateBy": null,
  "updateName": null,
  "isencryption": null,
  "isdistribution": null,
  "semester": "7796",
  "volume": "77960002",
  "remark": null,
  "isdel": "0",
  "useTimes": null,
  "knowledgeCode": null,
  "istopic": "",
  "source": "web",
  "needImg": null,
  "unitCode": null,
  "unitName": null,
  "paperResource": null
}
